const BING_AUTOSEARCH = {
    elements: {
        button: {
            start: document.getElementById("btn-start"),
            stop: document.getElementById("btn-stop")
        },
        select: {
            limit: document.getElementById("slc-limit"),
            interval: document.getElementById("slc-interval"),
            multitab: document.getElementById("slc-multitab"),
        },
        span: {
            progress: document.getElementById("span-progress"),
        },
        div: {
            settings: document.getElementById("div-settings"),
            timer: document.getElementById("div-timer"),
            bing: document.getElementById("div-bing")
        }
    },
    cookies: {
        set: (name, value, expires) => {
            try {
                let d = new Date();
                d.setTime(d.getTime() + (expires * 24 * 60 * 60 * 1000));

                let cookie = `${name}=${value};expires=${d.toUTCString()};path=/`;

                document.cookie = cookie;
            }
            catch (e) { }
        },
        get: (name) => {
            let value = null;

            try {
                let cookies = document.cookie.split(';');

                cookies.forEach((cookie) => {
                    if ((cookie + "=").trim().indexOf(name) == 0)
                        value = cookie.substring(name.length + 2, cookie.length);
                });
            }
            catch (e) { }

            return { name, value };
        },
        load: () => {
            let modal_help = new bootstrap.Modal(document.getElementById('modal-help'), {});

            let _need_help = BING_AUTOSEARCH.cookies.get("_need_help");
            let _multitab_mode = BING_AUTOSEARCH.cookies.get("_multitab_mode");
            let _search_interval = BING_AUTOSEARCH.cookies.get("_search_interval");
            let _search_limit = BING_AUTOSEARCH.cookies.get("_search_limit");

            if (!_need_help.value) {
                modal_help.show();

                BING_AUTOSEARCH.cookies.set("_need_help", BING_AUTOSEARCH.search.multitab.toString(), 365);
            }

            if (!_search_interval.value) {
                modal_help.show();

                BING_AUTOSEARCH.cookies.set("_search_interval", BING_AUTOSEARCH.search.interval.toString(), 365);
            }
            else {
                BING_AUTOSEARCH.elements.select.interval.value = BING_AUTOSEARCH.search.interval = parseInt(_search_interval.value.toString());
            }

            if (!_search_limit.value) {
                modal_help.show();

                BING_AUTOSEARCH.cookies.set("_search_limit", BING_AUTOSEARCH.search.limit.toString(), 365);
            }
            else {
                BING_AUTOSEARCH.elements.select.limit.value = BING_AUTOSEARCH.search.limit = parseInt(_search_limit.value.toString());
            }

            if (!_multitab_mode.value) {
                (function (a) {
                    if ((/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i.test(a) || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0, 4))))
                        BING_AUTOSEARCH.elements.select.multitab.value = "true";
                })(navigator.userAgent || navigator.vendor || window.opera);

                BING_AUTOSEARCH.cookies.set("_multitab_mode", BING_AUTOSEARCH.elements.select.multitab.value, 365);
            }
            else {
                BING_AUTOSEARCH.elements.select.multitab.value = _multitab_mode.value;
                BING_AUTOSEARCH.search.multitab = (_multitab_mode.value === "true");
            }
        }
    },
    search: {
        limit: 35,
        interval: 10000,
        multitab: false,
        engine: {
            terms: {
                lists: [
                    ["overthehillganglosangeles.org",
"www.overthehillganglosangeles.org",
"ovriaxd.angelfire.com",
"oxcash.com",
"www.oxcash.com",
"oyundas.org",
"www.oyundas.org",
"p-angels.com",
"www.p-angels.com",
"p.videosz.com",
"pacinocash.com",
"www.pacinocash.com",
"pacoloca.angelfire.com",
"page-x.com",
"www.page-x.com",
"pagepeels.sexmoney.com",
"pages-angelfire.whowhere.com",
"paixaoasiatica.com",
"www.paixaoasiatica.com",
"paixaogay.com",
"www.paixaogay.com",
"pamela-sandersin.info",
"www.pamela-sandersin.info",
"pamswebcams.com",
"www.pamswebcams.com",
"pandemos.ccnwebcams.com",
"pantiehoseladies.blogtur.com",
"pantydirectory.com",
"www.pantydirectory.com",
"pantyhosetv.net",
"www.pantyhosetv.net",
"panzertraffic.com",
"www.panzertraffic.com",
"paparazzifilth.com",
"www.paparazzifilth.com",
"paraisowebcams.com",
"www.paraisowebcams.com",
"partie-privee.com",
"www.partie-privee.com",
"partners.adultadworld.com",
"passeilimitado.com",
"www.passeilimitado.com",
"passion.com",
"www.passion.com",
"paulsnetwork.com",
"www.paulsnetwork.com",
"payserve.com",
"www.payserve.com",
"pbjjqx.angelfire.com",
"pcangel.com",
"www.pcangel.com",
"pcash.wildmatch.com",
"peach-angel.com",
"www.peach-angel.com",
"peachangel.com",
"www.peachangel.com",
"peelads.hustler.com",
"pei-ads.playboy.com",
"penisbot.com",
"www.penisbot.com",
"penix.fr",
"www.penix.fr",
"peqotif.angelfire.com",
"perfect10.com",
"www.perfect10.com",
"perfectangels.org",
"www.perfectangels.org",
"perfectgirls.net",
"www.perfectgirls.net",
"performance-angel.com",
"www.performance-angel.com",
"persiankitty.com",
"www.persiankitty.com",
"persianwomen.info",
"www.persianwomen.info",
"personalcams.com",
"www.personalcams.com",
"pertunda.com",
"www.pertunda.com",
"pervertedwebcams.com",
"www.pervertedwebcams.com",
"pervnetwork.com",
"www.pervnetwork.com",
"pervygames.com",
"www.pervygames.com",
"petras-angels.de",
"www.petras-angels.de",
"ph-pics.phncdn.com",
"phallosdei.com",
"www.phallosdei.com",
"phatwebcams.com",
"www.phatwebcams.com",
"phil-flash.com",
"www.phil-flash.com",
"phone-angel.de",
"www.phone-angel.de",
"phoneangels.com",
"www.phoneangels.com",
"phonevirgin.com",
"www.phonevirgin.com",
"photo-angels.biz",
"www.photo-angels.biz",
"photo.voffka.com",
"www.photo.voffka.com",
"photonaturals.com",
"www.photonaturals.com",
"photos.cams.com",
"photos0.pop6.com",
"photos1.pop6.com",
"photos6.pop6.com",
"photos8.pop6.com",
"photosex.biz",
"www.photosex.biz",
"photosys.angelfire.com",
"photovirgins.com",
"www.photovirgins.com",
"pic.aebn.net",
"picahottie.com",
"www.picahottie.com",
"picgalleries.cummypantyhose.com",
"picladies.com",
"www.picladies.com",
"pics.youjizz.com",
"picxx.net",
"www.picxx.net",
"picxxnetwork.com",
"www.picxxnetwork.com",
"pimproll.com",
"www.pimproll.com",
"pimpwebcams.com",
"www.pimpwebcams.com",
"pin-up-angels.net",
"www.pin-up-angels.net",
"pinaccesscode.com",
"www.pinaccesscode.com",
"pinkbabes.net",
"www.pinkbabes.net",
"pinkvisualhdgalleries.com",
"www.pinkvisualhdgalleries.com",
"pinkvisualpad.com",
"www.pinkvisualpad.com",
"pinkwebcam.com",
"www.pinkwebcam.com",
"pinkytoy.com",
"www.pinkytoy.com",
"piporno.com",
"www.piporno.com",
"piradinhas.com",
"www.piradinhas.com",
"piwebcams.com",
"www.piwebcams.com",
"piwik.redtube.com",
"pix.sexyads.net",
"pix4dicks.com",
"www.pix4dicks.com",
"planet-katie.info",
"www.planet-katie.info",
"planetsexblogs.com",
"www.planetsexblogs.com",
"planetsuzy.org",
"www.planetsuzy.org",
"play-angel.com",
"www.play-angel.com",
"play-boom.com",
"www.play-boom.com",
"playblog.org",
"www.playblog.org",
"playblog.ws",
"www.playblog.ws",
"playboy.bg",
"www.playboy.bg",
"playboy.com",
"www.playboy.com",
"playboy.com.br",
"www.playboy.com.br",
"playboy.com.mx",
"www.playboy.com.mx",
"playboy.com.tw",
"www.playboy.com.tw",
"playboynet.playboy.com",
"playingboy.com",
"www.playingboy.com",
"playingmatures.com",
"www.playingmatures.com",
"playmatewebcams.com",
"www.playmatewebcams.com",
"playmatewebcams.streamray.com",
"playmymovie.com",
"www.playmymovie.com",
"pleasurecage.info",
"www.pleasurecage.info",
"plib.brazzers.com",
"plib.juggcrew.com",
"plugin-x.com",
"www.plugin-x.com",
"plumpchicks.net",
"www.plumpchicks.net",
"plumpersworld.com",
"www.plumpersworld.com",
"plumpteens.net",
"www.plumpteens.net",
"pod.infinitypersonals.com",
"pod.sexsearch.com",
"poisonangel.citymax.com",
"pokeherstars.com",
"www.pokeherstars.com",
"polandtoday.org",
"www.polandtoday.org",
"polish-angels.com",
"www.polish-angels.com",
"pop6.adultfriendfinder.com",
"popads.ero-advertising.com",
"popander.mobi",
"www.popander.mobi",
"popcash.net",
"www.popcash.net",
"popfree.adultcash.com",
"pops.ero-advertising.com",
"porn-disney.com",
"www.porn-disney.com",
"porn.mtree.com",
"porn.to",
"www.porn.to",
"porn2.com",
"www.porn2.com",
"pornaccess.com",
"www.pornaccess.com",
"pornattitude.com",
"www.pornattitude.com",
"www.porncash.de",
"www.porncash.tv",
"pornclub.com",
"www.pornclub.com",
"porndisney.com",
"www.porndisney.com",
"porngalleriesz.com",
"www.porngalleriesz.com",
"pornhost.com",
"www.pornhost.com",
"pornhublive.com",
"www.pornhublive.com",
"www.pornmail.com",
"porno-disney.com",
"www.porno-disney.com",
"porno-teens-free.com",
"www.porno-teens-free.com",
"pornobanner.com",
"www.pornobanner.com",
"pornofolies.com",
"www.pornofolies.com",
"pornohotvideos.com",
"www.pornohotvideos.com",
"pornoinside.com",
"www.pornoinside.com",
"www.pornoitalia.it",
"pornopim.com",
"www.pornopim.com",
"pornorama.com",
"www.pornorama.com",
"pornoxxxclips.com",
"www.pornoxxxclips.com",
"pornpicsmovies.net",
"www.pornpicsmovies.net",
"pornstarslikeitbig.co.uk",
"www.pornstarslikeitbig.co.uk",
"porntracker.com",
"www.porntracker.com",
"porntubedirect.info",
"www.porntubedirect.info",
"portaladelaide.com.br",
"www.portaladelaide.com.br",
"portalangels.com.sapo.pt",
"poseparty.com",
"www.poseparty.com",
"preggowebcams.com",
"www.preggowebcams.com",
"premierimagehosting.com",
"www.premierimagehosting.com",
"premium.pervnetwork.com",
"premiumhdv.com",
"www.premiumhdv.com",
"pretty-angels.de",
"www.pretty-angels.de",
"pretty-virgins.com",
"www.pretty-virgins.com",
"prettyvirgins.com",
"www.prettyvirgins.com",
"primebreasts.net",
"www.primebreasts.net",
"primecups.com",
"www.primecups.com",
"primecups.xlogz.com",
"primeskype.com",
"www.primeskype.com",
"princessblueyez.com",
"www.princessblueyez.com",
"privatamateure.com",
"www.privatamateure.com",
"private-angels.net",
"www.private-angels.net",
"privatecams.ws",
"www.privatecams.ws",
"privatelivewebcams.com",
"www.privatelivewebcams.com",
"privatesangels.com",
"www.privatesangels.com",
"privatewebcams.com",
"www.privatewebcams.com",
"pro-ana-angels.wetpaint.com",
"promo.aebn.net",
"promo.ashleyscandy.com",
"promo.badoink.com",
"promo.cravingcarmen.com",
"promo.diddylicious.com",
"promo.hdvbucks.com",
"promo.heidiscandy.com",
"promo.karenloveskate.com",
"promo.love-money.de",
"promo.moviemonster.com",
"promo.pimproll.com",
"promo.premiumpass.com",
"promo.shegotknockedup.com",
"promo.tristastevens.com",
"promos.fling.com",
"promos.meetlocals.com",
"prosexxx.com",
"www.prosexxx.com",
"protizer.net",
"www.protizer.net",
"proxy.poseparty.com",
"psbbanners.com",
"www.psbbanners.com",
"public.porn.fr",
"publicexposurephotos.com",
"www.publicexposurephotos.com",
"publicexposurepics.com",
"www.publicexposurepics.com",
"publicexposurepictures.com",
"www.publicexposurepictures.com",
"pubzone.virginradiothailand.com",
"pufisi.com",
"www.pufisi.com",
"pure-angel.net",
"www.pure-angel.net",
"puredee.com",
"www.puredee.com",
"purefaces.com",
"www.purefaces.com",
"purefuck.com",
"www.purefuck.com",
"purepov.com",
"www.purepov.com",
"pussisex.com",
"www.pussisex.com",
"pussy.com",
"www.pussy.com",
"pussy.org",
"www.pussy.org",
"pussybabes.net",
"www.pussybabes.net",
"pussygreen.com",
"www.pussygreen.com",
"pussyharem.com",
"www.pussyharem.com",
"putasconwebcams.com",
"www.putasconwebcams.com",
"putitasangelicales.com",
"www.putitasangelicales.com",
"qahkurm.angelfire.com",
"qoqoz.com",
"qualityporn.biz",
"www.qualityporn.biz",
"qualitysextube.com",
"www.qualitysextube.com",
"quewebcams.com",
"www.quewebcams.com",
"r.sex-toplista.zy.pl",
"rabbitsreviews.com",
"www.rabbitsreviews.com",
"rainbow.topbucks.com",
"ranks.sextracker.com",
"rapid-xxx.com",
"www.rapid-xxx.com",
"rarbg.com",
"www.rarbg.com",
"rasazrak.info",
"www.rasazrak.info",
"rashatemraa.com",
"www.rashatemraa.com",
"rateme.km.ru",
"real-virgins.net",
"www.real-virgins.net",
"real-wife-stories.com",
"www.real-wife-stories.com",
"realandnatural.com",
"www.realandnatural.com",
"realblacklesbians.com",
"www.realblacklesbians.com",
"realfatgirls.net",
"www.realfatgirls.net",
"realitykings.com",
"www.realitykings.com",
"realitykingsnetwork.com",
"www.realitykingsnetwork.com",
"realsexdates.com",
"www.realsexdates.com",
"realsexwebcams.com",
"www.realsexwebcams.com",
"realteengirlfriends.com",
"www.realteengirlfriends.com",
"realvirgin.com",
"www.realvirgin.com",
"recordedwebcams.com",
"www.recordedwebcams.com",
"redangel.hu",
"www.redangel.hu",
"redangels.se",
"www.redangels.se",
"redheadwebcams.com",
"www.redheadwebcams.com",
"redir.juicyads.com",
"redir.webshots.com",
"redirects.ero-advertising.com",
"redlightcenter.com",
"www.redlightcenter.com",
"redtube.com",
"www.redtube.com",
"reelgalleries.com",
"www.reelgalleries.com",
"refer1.outster.com",
"refer100.outster.com",
"refer102.outster.com",
"refer20.outster.com",
"refer25.outster.com",
"refer46.outster.com",
"refer85.outster.com",
"referral.topbucks.com",
"referral.vod.topbucks.com",
"rehgdia.angelfire.com",
"reihesg.angelfire.com",
"rejalsgays.info",
"www.rejalsgays.info",
"relationship-resources.com",
"www.relationship-resources.com",
"rencontres-webcams.com",
"www.rencontres-webcams.com",
"reseller.sexyads.com",
"rexmag.com",
"www.rexmag.com",
"richardkern.com",
"www.richardkern.com",
"rideyourcamels.info",
"www.rideyourcamels.info",
"rijpevrouwenwebcams.com",
"www.rijpevrouwenwebcams.com",
"rk.com",
"www.rk.com",
"rnosh.com",
"www.rnosh.com",
"robsxxx.com",
"www.robsxxx.com",
"roccomovies.net",
"www.roccomovies.net",
"ronsangels.com",
"www.ronsangels.com",
"rotanaz.com",
"www.rotanaz.com",
"royalbluemedia.com",
"www.royalbluemedia.com",
"rr1.outster.com",
"rr1.xxxcounter.com",
"rts.doublepimp.com",
"rts.phn.doublepimp.com",
"ru-traffic.com",
"www.ru-traffic.com",
"rudefuck.com",
"www.rudefuck.com",
"rumrunners.us",
"www.rumrunners.us",
"runawayangels.com",
"www.runawayangels.com",
"rusangels.net",
"www.rusangels.net",
"russian-virgin.us",
"www.russian-virgin.us",
"russianangels.com",
"www.russianangels.com",
"russianangels.info",
"www.russianangels.info",
"russianmistress.femdomworld.com",
"russianparadise.com",
"www.russianparadise.com",
"russianpornoxxx.com",
"www.russianpornoxxx.com",
"russiantwinksecrets.com",
"www.russiantwinksecrets.com",
"russianvirginz.com",
"www.russianvirginz.com",
"russianvirginz.info",
"www.russianvirginz.info",
"s-angel.net",
"www.s-angel.net",
"s-angels.com",
"www.s-angels.com",
"s.angelo.over-blog.org",
"s3xads.com",
"www.s3xads.com",
"s7lob.com",
"www.s7lob.com",
"s7lob.net",
"www.s7lob.net",
"saccyclones.angelfire.com",
"sadistikvirgin.fr.st",
"saharanights.info",
"www.saharanights.info",
"salamtakehoh.info",
"www.salamtakehoh.info",
"salasdewebcams.com",
"www.salasdewebcams.com",
"salopepoitrine.angelfire.com",
"sancdn.net",
"www.sancdn.net",
"sandralatina.com",
"www.sandralatina.com",
"sapphicangels.com",
"www.sapphicangels.com",
"saraangell.com",
"www.saraangell.com",
"sashafucksdasha.com",
"www.sashafucksdasha.com",
"sassy-angels.com",
"www.sassy-angels.com",
"sassyangel.com",
"www.sassyangel.com",
"sativarose.xlogz.com",
"savannavirgin.com",
"www.savannavirgin.com",
"saxumeda.angelfire.com",
"sboob.com",
"www.sboob.com",
"schizogirl.blogs.allocine.fr",
"school-virgins.net",
"www.school-virgins.net",
"schoolofvirgins.com",
"www.schoolofvirgins.com",
"score-video.com",
"www.score-video.com",
"scoreadate.com",
"www.scoreadate.com",
"scripts.adultcheck.com",
"scripts.mofos.com",
"sdfasdf.vangangelt.info",
"www.sea-angels.ru",
"search.sextracker.com",
"searchsexblogs.com",
"www.searchsexblogs.com",
"searchwebcams.com",
"www.searchwebcams.com",
"searchxfind.com",
"www.searchxfind.com",
"seavirgin.com",
"www.seavirgin.com",
"secehira.angelfire.com",
"secretbehindporn.com",
"www.secretbehindporn.com",
"secretfriendswebcams.com",
"www.secretfriendswebcams.com",
"secretlittle.com",
"www.secretlittle.com",
"secretteenvideo.com",
"www.secretteenvideo.com",
"secure.collegerules.com",
"secure.euro-angels.com",
"secure.hazehim.com",
"secure.itsgonnahurt.com",
"secure.myanalangel.com",
"secure.outinpublic.com",
"secure.watchmygf.com",
"secure.watchmygf.net",
"secure.wicked.com",
"secure1.stunningangels.com",
"seducedangel.com",
"www.seducedangel.com",
"seekbang.com",
"www.seekbang.com",
"seemygf.com",
"www.seemygf.com",
"seniorhousingvirginabeach.com",
"www.seniorhousingvirginabeach.com",
"sensexion.com",
"www.sensexion.com",
"sensualwriter.com",
"www.sensualwriter.com",
"seo1.org",
"www.seo1.org",
"seoprofit.biz",
"www.seoprofit.biz",
"serilobe.angelfire.com",
"serve.ads.chaturbate.com",
"serving.xxxwebtraffic.com",
"sesso-gratis.info",
"www.sesso-gratis.info",
"seventeenvideo.com",
"www.seventeenvideo.com",
"sex-and-animals.com",
"www.sex-and-animals.com",
"www.sex-explorer.com",
"sex-toplista.zy.pl",
"sex-tracker.com",
"www.sex-tracker.com",
"sex-tracker.de",
"www.sex-tracker.de",
"sex-watch.com",
"www.sex-watch.com",
"sex2inc.com",
"www.sex2inc.com",
"sexad.net",
"www.sexad.net",
"sexangels.net",
"www.sexangels.net",
"sexcess.net",
"www.sexcess.net",
"sexcount.de",
"www.sexcount.de",
"sexcounter.com",
"www.sexcounter.com",
"sexdildoking.com",
"www.sexdildoking.com",
"sexdisney.com",
"www.sexdisney.com",
"sexfg.com",
"www.sexfg.com",
"www.sexfind.com",
"sexhunter.x0.nl",
"sexinyourcity.com",
"www.sexinyourcity.com",
"www.sexleech.com",
"sexlist.com",
"www.sexlist.com",
"sexmaxx.com",
"www.sexmaxx.com",
"sexmoney.com",
"www.sexmoney.com",
"sexole.com",
"www.sexole.com",
"sexpeeper.com",
"www.sexpeeper.com",
"sexproadventures.com",
"www.sexproadventures.com",
"sexsearch.com",
"www.sexsearch.com",
"sexsearchtgp.com",
"www.sexsearchtgp.com",
"sexskype.za.pl",
"www.sexskype.za.pl",
"sextracker.com",
"www.sextracker.com",
"sextronix.com",
"www.sextronix.com",
"sextvx.com",
"www.sextvx.com",
"sexualblondes.net",
"www.sexualblondes.net",
"sexualpleasureguide.com",
"www.sexualpleasureguide.com",
"sexy.fling.com",
"sexyads.com",
"www.sexyads.com",
"www.sexyads.net",
"sexybunnylove.com",
"www.sexybunnylove.com",
"sexyfashions.angelcities.com",
"sexygirlbutts.com",
"www.sexygirlbutts.com",
"sexyhumorgames.com",
"www.sexyhumorgames.com",
"sexymaturethumbs.com",
"www.sexymaturethumbs.com",
"sexyoung.us",
"www.sexyoung.us",
"sexytout.com",
"www.sexytout.com",
"sexzoznamka.eu",
"www.sexzoznamka.eu",
"sf1-1.yobt.com",
"sf1-2.yobt.com",
"sf1-3.yobt.com",
"sf1-4.yobt.com",
"sf1-5.yobt.com",
"sfb2-1.yobt.com",
"sfb2-2.yobt.com",
"sfb2-3.yobt.com",
"sfb2-4.yobt.com",
"sfb2-5.yobt.com",
"shabbyvirgins.com",
"www.shabbyvirgins.com",
"shamelessangel.com",
"www.shamelessangel.com",
"sharday.us",
"www.sharday.us",
"shared.juicybucks.com",
"shareporno.com",
"www.shareporno.com",
"sheisangel.com",
"www.sheisangel.com",
"shelbyvirgin.com",
"www.shelbyvirgin.com",
"shemale-clubs.com",
"www.shemale-clubs.com",
"shemalebot.com",
"www.shemalebot.com",
"shemalemovies.us",
"www.shemalemovies.us",
"shemalepepper.com",
"www.shemalepepper.com",
"shemaleswebcams.com",
"www.shemaleswebcams.com",
"shinangel9.free.fr",
"shinyangels.com",
"www.shinyangels.com",
"shopgiggles.com",
"www.shopgiggles.com",
"showdeinfieles.com",
"www.showdeinfieles.com",
"showdewebcams.com.ar",
"www.showdewebcams.com.ar",
"showmewebcams.com",
"www.showmewebcams.com",
"showwebcams.com",
"www.showwebcams.com",
"shy-angels.over-blog.com",
"shy-virgins.com",
"www.shy-virgins.com",
"shyvirgin.net",
"www.shyvirgin.net",
"shyvirgins.com",
"www.shyvirgins.com",
"sicflics.com",
"www.sicflics.com",
"sidebar.angelfire.com",
"silkangels.com",
"www.silkangels.com",
"silkyangels.com",
"www.silkyangels.com",
"singlesadnetwork.com",
"www.singlesadnetwork.com",
"sinisterangel.com",
"www.sinisterangel.com",
"sinistercams.com",
"www.sinistercams.com",
"sinistercamslive.com",
"www.sinistercamslive.com",
"site.img.4tube.com",
"sksawi.info",
"www.sksawi.info",
"skype.nexxen.cz",
"skypecam.com",
"www.skypecam.com",
"skypecam.streamray.com",
"skypeofsex.over-blog.com",
"skypesex.over-blog.com",
"skypesex.ru",
"www.skypesex.ru",
"slavecomics.com",
"www.slavecomics.com",
"sleazyangels.com",
"www.sleazyangels.com",
"sleepingbitch.com",
"www.sleepingbitch.com",
"slickcams.com",
"www.slickcams.com",
"slothtraffic.com",
"www.slothtraffic.com",
"slumsluts.net",
"www.slumsluts.net",
"slutwebcams.com",
"smartmovies.net",
"www.smartmovies.net",
"smrd7.net",
"www.smrd7.net",
"smut-planet.com",
"www.smut-planet.com",
"smutbdsm.com",
"www.smutbdsm.com",
"smutwebcams.com",
"www.smutwebcams.com",
"socalmovies.com",
"www.socalmovies.com",
"socialsexnetwork.net",
"www.socialsexnetwork.net",
"softcore.xxxcounter.com",
"software.filestube.com",
"solocazzienormi.com",
"www.solocazzienormi.com",
"sologirlguide.com",
"www.sologirlguide.com",
"solotouch.com",
"www.solotouch.com",
"solowebcams.com.ar",
"www.solowebcams.com.ar",
"sophiassecrets.com",
"www.sophiassecrets.com",
"sotransexuais.com",
"www.sotransexuais.com",
"sovujva.angelfire.com",
"spunkysheets.com",
"www.spunkysheets.com",
"squirters0.thumblogger.com",
"srandel.com",
"www.srandel.com",
"srv.juiceadv.com",
"sss828.welovecpa.com",
"st.virgin.net",
"st3.xhamster.com",
"start.9hz.com",
"start.outster.com",
"start.sextracker.com",
"start.xxxcounter.com",
"stat.easydate.biz",
"stat.upforitnetworks.com",
"static.ads.crakmedia.com",
"static.ard.xxxblackbook.com",
"static.ccnwebcams.com",
"static.contents.sex-explorer.com",
"static.creatives.livejasmin.com",
"static.filestube.com",
"static.fleshlight.com",
"static.gfx.slickcams.com",
"static.gfx.streamate.com",
"static.gfx.streamen.com",
"static.ifa.camads.net",
"static.ifa.yobtcams.com",
"static.justhookup.com",
"static.kissteenclub.com",
"static.rarbg.com",
"static.sex-explorer.com",
"static.wickedcdn.com",
"static.xvideos.com",
"statm.the-adult-company.com",
"stats.adultrevenueservice.com",
"stats.adultswim.com",
"stats.boyfriendnetwork.com",
"stats.outster.com",
"stats.pimproll.com",
"stats.sextracker.com",
"stats.xxxkey.com",
"stats.xxxrewards.com",
"stats1.porntrack.com",
"stats3.porntrack.com",
"statstools.porn.fr",
"statsv3.carpediem.fr",
"stcontent.premiumhdv.com",
"steamtraffic.com",
"www.steamtraffic.com",
"stepnation.com",
"www.stepnation.com",
"stickywebcams.com",
"www.stickywebcams.com",
"stocking-divas.com",
"www.stocking-divas.com",
"stocking-pages.com",
"www.stocking-pages.com",
"stocking-porn.com",
"www.stocking-porn.com",
"store.playboy.com",
"straightboygalleries.com",
"www.straightboygalleries.com",
"strangeland.com",
"www.strangeland.com",
"strangeland.net",
"www.strangeland.net",
"strangeland.org",
"www.strangeland.org",
"strangelove.com.au",
"www.strangelove.com.au",
"strangewishes.com",
"www.strangewishes.com",
"stream.pussyharem.com",
"streamate.com",
"www.streamate.com",
"streamate.doublepimp.com",
"streamen.com",
"www.streamen.com",
"streaming.tv69.com",
"streamlivesex.com",
"www.streamlivesex.com",
"streamsex.com",
"www.streamsex.com",
"stripgalleries.net",
"www.stripgalleries.net",
"stunningangels.com",
"www.stunningangels.com",
"stx.banners.sextracker.com",
"stx.sextracker.com",
"stx0.sextracker.com",
"stx1.sextracker.com",
"stx10.sextracker.com",
"stx11.sextracker.com",
"stx12.sextracker.com",
"stx13.sextracker.com",
"stx14.sextracker.com",
"stx15.sextracker.com",
"stx2.sextracker.com",
"stx3.sextracker.com",
"stx4.sextracker.com",
"stx5.sextracker.com",
"stx6.sextracker.com",
"stx7.sextracker.com",
"stx8.sextracker.com",
"stx9.sextracker.com",
"stxbans.sextracker.com",
"sublimedirectory.com",
"www.sublimedirectory.com",
"suburbanwebcams.com",
"www.suburbanwebcams.com",
"sucarpeppergirls.info",
"www.sucarpeppergirls.info",
"sucksex.com",
"www.sucksex.com",
"sugarangels.com",
"www.sugarangels.com",
"suicideangel.com",
"www.suicideangel.com",
"sultanswomen.com",
"www.sultanswomen.com",
"sunny-thumbs.com",
"www.sunny-thumbs.com",
"super-virgin.online-golie-skachat.info",
"superporbbaa.ru",
"supertightvirgins.com",
"www.supertightvirgins.com",
"superwebcams.com",
"www.superwebcams.com",
"support.sextronix.com",
"swapfinder.com",
"www.swapfinder.com",
"swebcams.com",
"www.swebcams.com",
"sweet-angels.com",
"www.sweet-angels.com",
"sweet.sweet-angels.net",
"sweetangel.tv",
"www.sweetangel.tv",
"sweetdiscreet.com",
"www.sweetdiscreet.com",
"sweethotteens.com",
"www.sweethotteens.com",
"sweetkrissy.com",
"www.sweetkrissy.com",
"sweetvirgin.com",
"www.sweetvirgin.com",
"sweetvirgins.com",
"www.sweetvirgins.com",
"swissangels.ch",
"www.swissangels.ch",
"swolangedijk.angelfire.com",
"sxx.com",
"www.sxx.com",
"sybianvirgins.com",
"www.sybianvirgins.com",
"tac.xcams.com",
"takezoo.com",
"www.takezoo.com",
"tastyangels.com",
"www.tastyangels.com",
"tatagirls.com",
"www.tatagirls.com",
"tats.cybererotica.com",
"taxindecente.com",
"www.taxindecente.com",
"taylorbow.xlogz.com",
"tds.extrime-list.com",
"teachtwinks.com",
"www.teachtwinks.com",
"teen-gay-boys.net",
"www.teen-gay-boys.net",
"teen-mail.com",
"www.teen-mail.com",
"teen.imlive.com",
"teen.streamate.com",
"teen.xxxcounter.com",
"teenbookmark.com",
"www.teenbookmark.com",
"teenburg.com",
"www.teenburg.com",
"teencumdumpsters.com",
"www.teencumdumpsters.com",
"teendaporn.com",
"www.teendaporn.com",
"teenfunzone.com",
"www.teenfunzone.com",
"teenhost.net",
"www.teenhost.net",
"teens-list.net",
"www.teens-list.net",
"teens.teenssites.net",
"teens24h.com",
"www.teens24h.com",
"teenscoreclub.com",
"www.teenscoreclub.com",
"teensexmovs.com",
"www.teensexmovs.com",
"teensexreality.com",
"www.teensexreality.com",
"teensforcash.com",
"www.teensforcash.com",
"teensgotboobs.net",
"www.teensgotboobs.net",
"teenshorde.com",
"www.teenshorde.com",
"teenslikeitbig.com",
"www.teenslikeitbig.com",
"teenslikeitbig.info",
"www.teenslikeitbig.info",
"teensondicks.com",
"www.teensondicks.com",
"teenssites.net",
"www.teenssites.net",
"teeny.thumblogger.com",
"teenywebcams.com",
"www.teenywebcams.com",
"tel.adult-arab.com",
"telefonsexpalast.de",
"www.telefonsexpalast.de",
"temploangelina.com",
"www.temploangelina.com",
"temptingangels.org",
"www.temptingangels.org",
"tenderboys.net",
"www.tenderboys.net",
"tendervirgins.com",
"www.tendervirgins.com",
"tenmilliongalleries.com",
"www.tenmilliongalleries.com",
"teqajopi.angelfire.com",
"textad.eroticmatch.com",
"textad.sexsearch.com",
"textad.sexsearchcom.com",
"textad.xxxcupid.com",
"textad.xxxmatch.com",
"textads.adultadworld.com",
"textads.sexmoney.com",
"tgirlmeat.com",
"www.tgirlmeat.com",
"tgp.adultfriendfinder.com",
"tgp.pornaccess.com",
"tgptraffic.biz",
"www.tgptraffic.biz",
"tgzleif.angelfire.com",
"thatsfucked.org",
"www.thatsfucked.org",
"the-adult-company.com",
"www.the-adult-company.com",
"the.sextracker.com",
"theamourangels.com",
"www.theamourangels.com",
"theangelina.com",
"www.theangelina.com",
"theater.aebn.net",
"thecolorofangels.com",
"www.thecolorofangels.com",
"thefallenangels.webcindario.com",
"thefreenude.com",
"www.thefreenude.com",
"themeetlocal.com",
"www.themeetlocal.com",
"theotherside.adult.directnic.com",
"thepregnantsex.com",
"www.thepregnantsex.com",
"www.thesexcinema.com",
"thesocialsexnetwork.com",
"www.thesocialsexnetwork.com",
"thestrangeangels.com",
"www.thestrangeangels.com",
"thickbbwforum.com",
"www.thickbbwforum.com",
"thirdmovies.com",
"www.thirdmovies.com",
"thomasetvirginie.over-blog.com",
"thrixxx.com",
"www.thrixxx.com",
"thumblogger.com",
"www.thumblogger.com",
"thumbs.1stmovieclub.net",
"thumbs.ah-me.com",
"thumbs.ero-advertising.com",
"thumbs.juggworld.com",
"thumbs.lonely-wolf.com",
"thumbs.myhomeclip.com",
"thumbsweek.com",
"www.thumbsweek.com",
"tiasenwebcams.com.ar",
"www.tiasenwebcams.com.ar",
"tiavaswebcams.com",
"www.tiavaswebcams.com",
"tigershark.adultadworld.com",
"tight-virgins.com",
"www.tight-virgins.com",
"tightangels.com",
"www.tightangels.com",
"tightteela.com",
"www.tightteela.com",
"tightvirgins.com.ar",
"www.tightvirgins.com.ar",
"tinaangel.com",
"www.tinaangel.com",
"tiny-virginz.com",
"www.tiny-virginz.com",
"tinylittlevirgin.com",
"www.tinylittlevirgin.com",
"tinyvirgins.cjb.net",
"titflicks.com",
"www.titflicks.com",
"titsbrew.sex2inc.com",
"titten-kitty-natursekt.de",
"www.titten-kitty-natursekt.de",
"tnaflix.com",
"www.tnaflix.com",
"todoporn.com",
"www.todoporn.com",
"todowebcams.com",
"www.todowebcams.com",
"tokyoangels.com",
"www.tokyoangels.com",
"tools.pacinocash.com",
"tools.porn.fr",
"toonaddict.com",
"www.toonaddict.com",
"toons-for-adult.com",
"www.toons-for-adult.com",
"tootrash.com",
"www.tootrash.com",
"top-porn-sites.info",
"www.top-porn-sites.info",
"top.amateuralbum.net",
"top.angels-list.com",
"top.photo-angels.info",
"top.x--x--x.com",
"topadult.ro",
"www.topadult.ro",
"topadult10.com",
"www.topadult10.com",
"topamateurforum.com",
"www.topamateurforum.com",
"topamateursexvideos.com",
"www.topamateursexvideos.com",
"topbucks.com",
"www.topbucks.com",
"topfreaks.com",
"www.topfreaks.com",
"topheavywebcams.com",
"www.topheavywebcams.com",
"tophomevideos.com",
"www.tophomevideos.com",
"toplistwebcams.com",
"www.toplistwebcams.com",
"topmodel_virginie.cmonbook.com",
"topmomvideos.com",
"www.topmomvideos.com",
"topnotchwebcams.com",
"www.topnotchwebcams.com",
"toppornblogs.com",
"www.toppornblogs.com",
"topsexart.com",
"www.topsexart.com",
"topsites.naturalangels.com",
"topsites24.net",
"www.topsites24.net",
"topsiteuri.ro",
"www.topsiteuri.ro",
"toptoonsites.com",
"www.toptoonsites.com",
"topwebcams.com",
"www.topwebcams.com",
"tor.redlightcenter.com",
"torontoangels.com",
"www.torontoangels.com",
"torture.adult-extreme.com",
"totalexposure.com",
"www.totalexposure.com",
"toteme.com",
"www.toteme.com",
"tour.brazzers.com",
"tour.cybererotica.com",
"tour.ihookup.com",
"tours.playboy.com",
"tr-af.com",
"www.tr-af.com",
"track.adultdialersolution.com",
"track.fling.com",
"track.justhookup.com",
"track.pornaccess.com",
"track.realitykings.com",
"track.vscash.com",
"track.xtrasize.nl",
"tracker.ero-advertising.com",
"tracking.fanbridge.com",
"tradehardlinks.com",
"www.tradehardlinks.com",
"tradgardshus.angelfire.com",
"traffic.ru",
"www.traffic.ru",
"trafficholder.com",
"www.trafficholder.com",
"trailerwmv.com",
"www.trailerwmv.com",
"trampararam.net",
"www.trampararam.net",
"tranceangel.startmee.nl",
"tranent.nl",
"www.tranent.nl",
"trannypichunter.com",
"www.trannypichunter.com",
"trans-angelina.de",
"www.trans-angelina.de",
"transexual-webcams.com",
"www.transexual-webcams.com",
"transladyboy.com",
"www.transladyboy.com",
"transsexualhut.com",
"www.transsexualhut.com",
"travestisconwebcams.com",
"www.travestisconwebcams.com",
"trial.sex-explorer.com",
"triplexangels.com",
"www.triplexangels.com",
"triplexposure.com",
"www.triplexposure.com",
"trueangels.com",
"www.trueangels.com",
"truecash.com",
"www.truecash.com",
"tsdreamangel.com",
"www.tsdreamangel.com",
"tuakcba.angelfire.com",
"tube8.com",
"www.tube8.com",
"tubeanalporn.com",
"www.tubeanalporn.com",
"tubepornteen.com",
"www.tubepornteen.com",
"tuccus.com",
"www.tuccus.com",
"tukejrh.angelfire.com",
"turbo-angels.forummotion.com",
"tv69.com",
"www.tv69.com",
"tvclubtour.playboy.com",
"twatgod.com",
"www.twatgod.com",
"twilight-angels.com",
"www.twilight-angels.com",
"twinksonwebcams.com",
"www.twinksonwebcams.com",
"twistedblogs.com",
"www.twistedblogs.com",
"tyme2play.ucgalleries.com",
"ucgalleries.com",
"www.ucgalleries.com",
"uk-webcams.com",
"www.uk-webcams.com",
"ultra-pornstars.com",
"www.ultra-pornstars.com",
"ultrawebcams.com",
"www.ultrawebcams.com",
"unitedtechguys.com",
"www.unitedtechguys.com",
"unshavedwebcams.com",
"www.unshavedwebcams.com",
"unuzroe.angelfire.com",
"updatenationwide.9hz.com",
"upforit.com",
"www.upforit.com",
"upforitnetworks.com",
"www.upforitnetworks.com",
"usa-webcams.com",
"www.usa-webcams.com",
"usasexlovers.com",
"www.usasexlovers.com",
"usearchx.com",
"www.usearchx.com",
"usercash.com",
"www.usercash.com",
"users.dacash.com",
"usualgirls.com",
"www.usualgirls.com",
"usvirgin.com",
"www.usvirgin.com",
"usvirgins.com",
"www.usvirgins.com",
"utherverse.com",
"www.utherverse.com",
"v3.allurecash.net",
"va-ua.com",
"www.va-ua.com",
"van.redlightcenter.com",
"veraezz.angelfire.com",
"verbalangels.com",
"www.verbalangels.com",
"veronicasdiary.com",
"www.veronicasdiary.com",
"verwebcams.com",
"www.verwebcams.com",
"verydemotivational.memebase.com",
"veryvirgin.com",
"www.veryvirgin.com",
"vette-porno.nl",
"www.vette-porno.nl",
"viacrux.angelfire.com",
"viagra-shop.com.ua",
"www.viagra-shop.com.ua",
"vibrasian.com",
"www.vibrasian.com",
"vickyvirgin.com",
"www.vickyvirgin.com",
"vidbang.com",
"www.vidbang.com",
"video-angels.ru.tf",
"video-porno-gratuit.pornofolies.com",
"video-virgin.net",
"www.video-virgin.net",
"video-virgins.com",
"www.video-virgins.com",
"video.filestube.com",
"video69.ru",
"www.video69.ru",
"videoangels.com",
"www.videoangels.com",
"videodirectory10.info",
"www.videodirectory10.info",
"videos2stars.com",
"www.videos2stars.com",
"videos666.com",
"www.videos666.com",
"videosexperts.com",
"www.videosexperts.com",
"videoso.withsex.com",
"videosywebcams.com",
"www.videosywebcams.com",
"videosz.com",
"www.videosz.com",
"videovirgins.com",
"www.videovirgins.com",
"vidz.com",
"www.vidz.com",
"villoumoristic.blogs.allocine.fr",
"vipangelz.com",
"www.vipangelz.com",
"virgin-cocks.com",
"www.virgin-cocks.com",
"virgin-coconut-oil.info",
"www.virgin-coconut-oil.info",
"virgin-experience.com",
"www.virgin-experience.com",
"virgin-films.com",
"www.virgin-films.com",
"virgin-international.de",
"www.virgin-international.de",
"virgin-movies.com",
"www.virgin-movies.com",
"virgin-nubiles.com",
"www.virgin-nubiles.com",
"virgin-paradise.com",
"www.virgin-paradise.com",
"virgin-paradize.com",
"www.virgin-paradize.com",
"virgin-pics.com",
"www.virgin-pics.com",
"virgin-tv.tv",
"www.virgin-tv.tv",
"virgin-world.com",
"www.virgin-world.com",
"virgin.cjbb.net",
"virgin.inq.com",
"virgin.online-golie-skachat.info",
"virgin4free.com",
"www.virgin4free.com",
"virgin50.com",
"www.virgin50.com",
"virgin66.freehostpage.com",
"virginalena.com",
"www.virginalena.com",
"virginals.com",
"www.virginals.com",
"virginanime.com",
"www.virginanime.com",
"virginass.com",
"www.virginass.com",
"virginbody.com",
"www.virginbody.com",
"virgincards.com",
"www.virgincards.com",
"virgincity.com",
"www.virgincity.com",
"virginconfession.com",
"www.virginconfession.com",
"virgindot.com",
"www.virgindot.com",
"virginfestival2008.com",
"www.virginfestival2008.com",
"virginfilms.com",
"www.virginfilms.com",
"virginfisters.net",
"www.virginfisters.net",
"virginfriend.info",
"www.virginfriend.info",
"virgingalactic.ca",
"www.virgingalactic.ca",
"virgingaming.com",
"www.virgingaming.com",
"virginhaven.com",
"www.virginhaven.com",
"virginhigh.com",
"www.virginhigh.com",
"virginhoney.com",
"www.virginhoney.com",
"virginhood.com",
"www.virginhood.com",
"virginia-model.info",
"www.virginia-model.info",
"virginia-personals.com",
"www.virginia-personals.com",
"virginia-the-model.book.fr",
"virginia.in",
"www.virginia.in",
"virginia.lover.free.fr",
"virginia.newmail.ru",
"virginiaannterrell.net",
"www.virginiaannterrell.net",
"virginiabeachattorneyinfo.com",
"www.virginiabeachattorneyinfo.com",
"virginiablueridge.com",
"www.virginiablueridge.com",
"virginiadiocese.org",
"www.virginiadiocese.org",
"virginiasanden.deviantart.com",
"virginiasteger.com",
"www.virginiasteger.com",
"virginiatechmurders.com",
"www.virginiatechmurders.com",
"virginidad.com",
"www.virginidad.com",
"virginidad.nl",
"www.virginidad.nl",
"virginie.daviaud.free.fr",
"virginie.efira.free.fr",
"virginie.efira.nue.online.fr",
"virginie.efira.online.fr",
"virginie.elfira.online.fr",
"virginie.et.karl.free.fr",
"virginie.ledoyen.online.fr",
"virginiecaprice.com",
"www.virginiecaprice.com",
"virginieh.cmonbook.com",
"virginietvsoumise.photo.doctissimo.fr",
"virgininterview.com",
"www.virgininterview.com",
"virginity.fun.ms",
"virginkitty.com",
"www.virginkitty.com",
"virginladies.com",
"www.virginladies.com",
"virginlove.mistypark.com",
"virginmaleass.com",
"www.virginmaleass.com",
"virginmedia.ed10.net",
"virginmedianet.com",
"www.virginmedianet.com",
"virginmobile.fr",
"www.virginmobile.fr",
"virginmobileringtones.weebly.com",
"virginnextdoor.com",
"www.virginnextdoor.com",
"virginoff.biz",
"www.virginoff.biz",
"virginoff.co.uk",
"www.virginoff.co.uk",
"virginoff.com",
"www.virginoff.com",
"virginoff.com.ar",
"www.virginoff.com.ar",
"virginoff.info",
"www.virginoff.info",
"virginopener.com",
"www.virginopener.com",
"virginpalace.de",
"www.virginpalace.de",
"virginpass.com",
"www.virginpass.com",
"virginpassword.com",
"www.virginpassword.com",
"virginphoto.com",
"www.virginphoto.com",
"virginplace.com",
"www.virginplace.com",
"virginradio.fr",
"www.virginradio.fr",
"virginriches.com",
"www.virginriches.com",
"virginriver.com",
"www.virginriver.com",
"virgins-candid.com",
"www.virgins-candid.com",
"virgins-club.com",
"www.virgins-club.com",
"virgins-off.com",
"www.virgins-off.com",
"virgins-x.com",
"www.virgins-x.com",
"virgins.allcj.com",
"virgins.fsn.net",
"virgins.info",
"www.virgins.info",
"virgins.org",
"www.virgins.org",
"virgins.pl",
"www.virgins.pl",
"virgins19.com",
"www.virgins19.com",
"virgins4free.com",
"www.virgins4free.com",
"virgins4freegold.com",
"www.virgins4freegold.com",
"virginsadist.com",
"www.virginsadist.com",
"virginsbbs.com",
"www.virginsbbs.com",
"virginsblog.com",
"www.virginsblog.com",
"virginsclub.com",
"www.virginsclub.com",
"virginsclub.net",
"www.virginsclub.net",
"virginscrazy.com",
"www.virginscrazy.com",
"virginsdontskydive.com",
"www.virginsdontskydive.com",
"virginseries.com",
"www.virginseries.com",
"virginsexstory.com",
"www.virginsexstory.com",
"virginsexweb.com",
"www.virginsexweb.com",
"virginsexx.com",
"www.virginsexx.com",
"virginsfresh.com",
"www.virginsfresh.com",
"virginshack.com",
"www.virginshack.com",
"virginshow.com",
"www.virginshow.com",
"virginsisterdotcum.com",
"www.virginsisterdotcum.com",
"virginslits.com",
"www.virginslits.com",
"virginsmag.com",
"www.virginsmag.com",
"virginsmania.com",
"www.virginsmania.com",
"virginsnack.com",
"www.virginsnack.com",
"virginsrus.com",
"www.virginsrus.com",
"virginstories.com",
"www.virginstories.com",
"virginsuicide.com",
"www.virginsuicide.com",
"virginsvids.com",
"www.virginsvids.com",
"virgintemple.com",
"www.virgintemple.com",
"virgintime.com",
"www.virgintime.com",
"virgintwat.com",
"www.virgintwat.com",
"virginworld.mylivepage.ru",
"virginx.com",
"www.virginx.com",
"virginz.info",
"www.virginz.info",
"virginz.net",
"www.virginz.net",
"virginz.nl",
"www.virginz.nl",
"virginz.tv",
"www.virginz.tv",
"virginzinfo4.ye.st",
"virtuagirlhd.com",
"www.virtuagirlhd.com",
"virtuangels.com",
"www.virtuangels.com",
"vis.sexlist.com",
"vis5.sexlist.com",
"visodangelo.com",
"www.visodangelo.com",
"vod.topbucks.com",
"voffka.com",
"www.voffka.com",
"voktel.com",
"www.voktel.com",
"voluptuous.naturalwonderz.com",
"voyeurpornweb.com",
"www.voyeurpornweb.com",
"voyeurweb.com",
"www.voyeurweb.com",
"vozer.voffka.com",
"vporn.com",
"www.vporn.com",
"vuioirq.angelfire.com",
"walking-angel.com",
"www.walking-angel.com",
"wank.net",
"www.wank.net",
"wankerhut.com",
"www.wankerhut.com",
"war2kotshena.info",
"www.war2kotshena.info",
"wastedamateurs.com",
"www.wastedamateurs.com",
"watchmygf.com",
"www.watchmygf.com",
"watchmygf.net",
"www.watchmygf.net",
"watchporn.com",
"www.watchporn.com",
"wbaiema.angelfire.com",
"wbfbyr.angelfire.com",
"web-angels.de",
"www.web-angels.de",
"webcams.com",
"www.webcams.com",
"webcamsdancer.com",
"www.webcamsdancer.com",
"webcamtop100.com",
"www.webcamtop100.com",
"webdata.vidz.com",
"webmaster.privatamateure.com",
"webmaster.topbucks.com",
"webmaster.worldsex.com",
"webmasters.flipscash.com",
"webmasters.h2porn.com",
"webmasters.hugetraffic.com",
"webmasters.nastydollars.com",
"webmasters.sextracker.com",
"webtraffic.se",
"www.webtraffic.se",
"welcome.ivanafukalot.com",
"welcome.sashafucksdasha.com",
"welve6.angelfire.com",
"wendise.com",
"www.wendise.com",
"wetangels.com",
"www.wetangels.com",
"wetvirgin.net",
"www.wetvirgin.net",
"wetvirgins.com",
"www.wetvirgins.com",
"wetwebcams.com",
"www.wetwebcams.com",
"whatpornsite.com",
"www.whatpornsite.com",
"white.sexer.com",
"wicked.com",
"www.wicked.com",
"wickedpictures.com",
"www.wickedpictures.com",
"wifeysworld.ws",
"www.wifeysworld.ws",
"wikiangela.com",
"www.wikiangela.com",
"wild-teenz.com",
"www.wild-teenz.com",
"wildebonylovers.com",
"www.wildebonylovers.com",
"wildxangel.com",
"www.wildxangel.com",
"wiredpussy.com",
"www.wiredpussy.com",
"wisevirgin.com",
"www.wisevirgin.com",
"wm.banners.sextracker.com",
"wolrdteenparadise.com",
"www.wolrdteenparadise.com",
"women-pickup.com",
"www.women-pickup.com",
"womenofplayboy.com",
"www.womenofplayboy.com",
"won.images.streamray.com",
"wooyeoh.angelfire.com",
"world4angelina.com",
"www.world4angelina.com",
"worlddatingforum.com",
"www.worlddatingforum.com",
"worldsex.com",
"www.worldsex.com",
"worthymoms.com",
"www.worthymoms.com",
"wqw.planetsuzy.org",
"wt.eroticmatch.com",
"wt.sexsearch.com",
"wt.sexsearchcom.com",
"wt.xxxcupid.com",
"wtfpeople.com",
"www.wtfpeople.com",
"wts.sexrouter.net",
"wunbuck.com",
"www.wunbuck.com",
"wvasilevcampers.krovatka.su",
"ww.angelswifelovers.com",
"ww1.massiveaccess-cartoonx.com",
"www-old.hugetraffic.com",
"www-old.nastydollars.com",
"www1.chickenhost.com",
"www1.darikweb.com",
"www1.sexinyourcity.com",
"www16.japaneseanime.com",
"www2.barebree.com",
"www2.chickenhost.com",
"www2.unionfilesexchnges.su",
"www3.chickenhost.com",
"www4.chickenhost.com",
"www5.chickenhost.com",
"wwwalisonangel.com",
"www.wwwalisonangel.com",
"x--x--x.com",
"www.x--x--x.com",
"x-bangbus.bangbros1.com",
"x-bigmouthfuls.bangbros1.com",
"x-bigtitsroundasses.bangbros1.com",
"x-milflessons.bangbros1.com",
                "Google",
"YouTube",
"Facebook",
"Amazon",
"Wikipedia",
"Twitter",
"Instagram",
"Netflix",
"Reddit",
"LinkedIn",
"eBay",
"Pinterest",
"Microsoft",
"Apple",
"CNN",
"BBC",
"The New York Times",
"Forbes",
"Bloomberg",
"Yahoo",
"Tumblr",
"WordPress",
"BuzzFeed",
"ESPN",
"IMDb",
"Spotify",
"Twitch",
"Airbnb",
"Booking.com",
"TripAdvisor",
"PayPal",
"Alibaba",
"Vimeo",
"Dropbox",
"Medium",
"Quora",
"National Geographic",
"TED",
"WebMD",
"The Guardian",
"Mashable",
"CNBC",
"Fox News",
"Business Insider",
"CNBC",
"Reuters",
"Adobe",
"GitHub",
"Khan Academy",
"Udemy",
"Coursera",
"Stack Overflow",
"SoundCloud",
"BBC Good Food",
"Allrecipes",
"Zillow",
"Etsy",
"9GAG",
"Giphy",
"Duolingo",
"Adobe",
"BBC Sport",
"CNN Business",
"CNBC",
"Fox Business",
"Reuters",
"The Wall Street Journal",
"The Economist",
"National Geographic",
"TED",
"WebMD",
"Mayo Clinic",
"Healthline",
"Harvard Health",
"The Guardian",
"The Independent",
"Mashable",
"BuzzFeed News",
"The Huffington Post",
"TechCrunch",
"Wired",
"Gizmodo",
"Mashable",
"The Verge",
"CNET",
"PCMag",
"Engadget",
"Ars Technica",
"IGN",
"GamesRadar",
"Polygon",
"Kotaku",
"GameSpot",
"Variety",
"Rolling Stone",
"Pitchfork",
"Billboard",
"NME",
"Genius",
"Metro Lyrics",
"Ultimate Guitar",
"Apartment Therapy",
"Houzz",
"Architectural Digest",
"Curbed",
"HomeAdvisor",
"Angie's List",
"Wayfair",
"Overstock",
"Houzz",
"Houzz",
"The Spruce",
"The Knot",
"WeddingWire",
"Brides",
"The Dodo",
"Petfinder",
"Chewy",
"Petco",
"PetSmart",
"Rover",
"Wag!",
"BarkBox",
"Purina",
"Blue Buffalo",
"Tasty",
"Allrecipes",
"Food Network",
"Bon Appétit",
"Epicurious",
"Martha Stewart",
"Serious Eats",
"Delish",
"Betty Crocker",
"Kraft Recipes",
"BBC Good Food",
"Food52",
"Yelp",
"TripAdvisor",
"Zomato",
"OpenTable",
"Grubhub",
"Seamless",
"DoorDash",
"Uber Eats",
"Postmates",
"Instacart",
"Shipt",
"Walmart Grocery",
"Target",
"Best Buy",
"eBay",
"Etsy",
"Overstock",
"Wayfair",
"Newegg",
"Alibaba",
"AliExpress",
"Banggood",
"Gearbest",
"DHgate",
"LightInTheBox",
"Wish",
"ASOS",
"Zara",
"H&M",
"Forever 21",
"Fashion Nova",
"Boohoo",
"Shein",
"PrettyLittleThing",
"Missguided",
"Revolve",
"Net-a-Porter",
"MatchesFashion",
"SSENSE",
"Farfetch",
"StockX",
"GOAT",
"Flight Club",
"Stadium Goods",
"KicksOnFire",
"Sneaker News",
"Hypebeast",
"Highsnobiety",
"Complex",
"Sneaker Bar Detroit",
"Nice Kicks",
"Sole Collector",
"Freshness Mag",
"The Sole Supplier",
"Sneaker Freaker",
"Footwear News",
"SneakerFiles",
"JustFreshKicks",
"Sneaker Politics",
"Modern Notoriety",
"Kicks Deals",
"House of Heat",
"The Shoe Game",
"Apple",
"Banana",
"Car",
"Dog",
"Elephant",
"Fish",
"Guitar",
"House",
"Ice cream",
"Jellyfish",
"Kangaroo",
"Lamp",
"Monkey",
"Notebook",
"Orange",
"Piano",
"Queen",
"Rabbit",
"Sun",
"Table",
"Umbrella",
"Violin",
"Watermelon",
"Xylophone",
"Yak",
"Zebra",
"Anchor",
"Book",
"Cat",
"Door",
"Elephant",
"Frog",
"Guitar",
"Hat",
"Ice",
"Jacket",
"Kite",
"Lemon",
"Mango",
"Nest",
"Octopus",
"Penguin",
"Queen",
"Rabbit",
"Sun",
"Tree",
"Umbrella",
"Van",
"Water",
"Xylophone",
"Yo-yo",
"Zucchini",
"Ant",
"Ball",
"Clock",
"Duck",
"Egg",
"Flower",
"Goat",
"Hat",
"Ice cream",
"Jacket",
"Kite",
"Lion",
"Moon",
"Nest",
"Owl",
"Pineapple",
"Quail",
"Rainbow",
"Strawberry",
"Turtle",
"Unicorn",
"Volleyball",
"Whale",
"Xbox",
"Yogurt",
"Zebra",
"Anchor",
"Bird",
"Carrot",
"Dinosaur",
"Elephant",
"Feather",
"Guitar",
"Hammer",
"Igloo",
"Jacket",
"Kangaroo",
"Ladder",
"Mouse",
"Nut",
"Octopus",
"Pizza",
"Quilt",
"Rainbow",
"Snowman",
"Tiger",
"Unicorn",
"Violin",
"Wagon",
"Xylophone",
"Yak",
"Zucchini",
"Apple",
"Butterfly",
"Cat",
"Dolphin",
"Eggplant",
"Frog",
"Gorilla",
"Horse",
"Ice cream",
"Jellyfish",
"Koala",
"Lemon",
"Monkey",
"Narwhal",
"Octopus",
"Penguin",
"Quokka",
"Rabbit",
"Shark",
"Tiger",
"Umbrella",
"Vulture",
"Walrus",
"X-ray",
"Yak",
"Zebra",
"Antelope",
"Bear",
"Crocodile",
"Duck",
"Elephant",
"Fox",
"Giraffe",
"Hippopotamus",
"Iguana",
"Jaguar",
"Kangaroo",
"Lion",
"Mouse",
"Newt",
"Ostrich",
"Peacock",
"Quail",
"Rabbit",
"Snake",
"Tiger",
"Unicorn",
"Vulture",
"Walrus",
"Xerus",
"Yak",
"Zebra",
"Ant",
"Bear",
"Cat",
"Dog",
"Elephant",
"Fox",
"Goat",
"Horse",
"Iguana",
"Jaguar",
"Koala",
"Lion",
"Monkey",
"Narwhal",
"Owl",
"Penguin",
"Quail",
"Rabbit",
"Shark",
"Tiger",
"Umbrella",
"Vulture",
"Walrus",
"Xerus",
"Yak",
"Zebra",
"Antelope",
"Bear",
"Crocodile",
"Duck",
"Elephant",
"Fox",
"Gorilla",
"Hippopotamus",
"Iguana",
"Jaguar",
"Kangaroo",
"Lion",
"Mouse",
"Newt",
"Ostrich",
"Peacock",
"Quail",
"Rabbit",
"The Witcher 3: Wild Hunt",
"Grand Theft Auto V",
"Red Dead Redemption 2",
"Minecraft",
"Counter-Strike: Global Offensive",
"Among Us",
"Fortnite",
"Apex Legends",
"League of Legends",
"Valorant",
"Call of Duty: Warzone",
"Rainbow Six Siege",
"Cyberpunk 2077",
"PUBG (PlayerUnknown's Battlegrounds)",
"DOTA 2",
"Rocket League",
"Destiny 2",
"Team Fortress 2",
"Skyrim (The Elder Scrolls V: Skyrim)",
"Fall Guys: Ultimate Knockout",
"Stardew Valley",
"Overwatch",
"Assassin's Creed Valhalla",
"Far Cry 5",
"The Sims 4",
"Hitman 3",
"Genshin Impact",
"Resident Evil Village",
"Battlefield V",
"Tom Clancy's Ghost Recon Breakpoint",
"Watch Dogs: Legion",
"Final Fantasy XIV",
"Monster Hunter: World",
"Death Stranding",
"Dark Souls III",
"DOOM Eternal",
"Control",
"Diablo III",
"Cities: Skylines",
"Total War: Three Kingdoms",
"Civilization VI",
"Planet Zoo",
"Euro Truck Simulator 2",
"Microsoft Flight Simulator",
"No Man's Sky",
"Satisfactory",
"Subnautica",
"ARK: Survival Evolved",
"Rust",
"Terraria",
"Phasmophobia",
"Dead by Daylight",
"Borderlands 3",
"The Outer Worlds",
"Divinity: Original Sin 2",
"Warframe",
"Path of Exile",
"Forza Horizon 4",
"F1 2020",
"Dirt Rally 2.0",
"NBA 2K21",
"FIFA 21",
"Madden NFL 21",
"Tony Hawk's Pro Skater 1 + 2",
"Fall Guys: Ultimate Knockout",
"Hades",
"Disco Elysium",
"Ori and the Will of the Wisps",
"Hollow Knight",
"Celeste",
"Cuphead",
"Ori and the Blind Forest",
"Undertale",
"Inside",
"Little Nightmares",
"A Plague Tale: Innocence",
"Control",
"Resident Evil 7: Biohazard",
"Prey",
"Alien: Isolation",
"Metro Exodus",
"The Evil Within 2",
"Outlast 2",
"Amnesia: Rebirth",
"Layers of Fear 2",
"SOMA",
"Blair Witch",
"The Forest",
"Phasmophobia",
"DayZ",
"Seven Days to Die",
"The Long Dark",
"Conan Exiles",
"Don't Starve Together",
"Raft",
"Grounded",
"The Escapists 2",
"Human: Fall Flat",
"Overcooked! 2",
"Moving Out",
"Phasmophobia",
"Dead by Daylight",
"Among Us",
"Secret Neighbor",
"Friday the 13th: The Game",
"Golf With Your Friends",
"Gang Beasts",
"Fall Guys: Ultimate Knockout",
"Tricky Towers",
"TowerFall Ascension",
"Stick Fight: The Game",
"Ultimate Chicken Horse",
"Worms W.M.D",
"Duck Game",
"SpeedRunners",
"Keep Talking and Nobody Explodes",
"Risk of Rain 2",
"Terraria",
"Starbound",
"Don't Starve Together",
"Stardew Valley",
"Minecraft",
"Portal 2",
"Human: Fall Flat",
"The Jackbox Party Pack",
"Tabletop Simulator",
"Golf It!",
"Barotrauma",
"Deep Rock Galactic",
"Sea of Thieves",
"Elite Dangerous",
"No Man's Sky",
"Star Wars: Squadrons",
"EVE Online",
"War Thunder",
"Microsoft Flight Simulator",
"DCS World",
"Ace Combat 7: Skies Unknown",
"X-Plane 11",
"IL-2 Sturmovik: Great Battles",
"World of Warplanes",
"FlightGear",
"Kerbal Space Program",
"Farming Simulator 19",
"Euro Truck Simulator 2",
"American Truck Simulator",
"SnowRunner",
"Train Sim World 2",
"Microsoft Train Simulator",
"Open Rails",
"Train Simulator 2021",
"Transport Fever 2",
"Railway Empire",
"Trainz Railroad Simulator 2019",
"Railroad Corporation",
"Flight Simulator X",
"Assetto Corsa",
"Project CARS 3",
"Gran Turismo 7",
"Forza Motorsport 7",
"F1 2020",
"Dirt Rally 2.0",
"WRC 9",
"NASCAR Heat 5",
"iRacing",
"rFactor 2",
"Automobilista 2",
"KartKraft",
"BeamNG.drive",
"Assetto Corsa Competizione",
"Project CARS 2",
"Gran Turismo Sport",
"Forza Horizon 4",
"Need for Speed Heat",
"GRID",
"DiRT 4",
"WRC 8",
"F1 2019",
"NASCAR Heat 4",
"Monster Energy Supercross - The Official Videogame 3",
"MotoGP 20",
"Ride 4",
"MXGP 2020 - The Official Motocross Videogame",
"TT Isle of Man: Ride on the Edge 2",
"SnowRunner",
"Spintires",
"BeamNG.drive",
"MudRunner",
"Farming Simulator 19",
"Euro Truck Simulator 2",
"American Truck Simulator",
"Bus Simulator 18",
"Train Simulator 2021",
"OMSI 2",
"Train Sim World 2",
"Microsoft Flight Simulator",
"Kerbal Space Program",
"FlightGear",
"DCS World",
"X-Plane 11",
"The Godfather",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"The Lord of the Rings: The Return of the King",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas",
"The Silence of the Lambs",
"Star Wars: Episode V - The Empire Strikes Back",
"The Lord of the Rings: The Fellowship of the Ring",
"Saving Private Ryan",
"The Green Mile",
"The Godfather: Part II",
"Gladiator",
"The Departed",
"Titanic",
"The Lord of the Rings: The Two Towers",
"Interstellar",
"The Prestige",
"The Lion King",
"Se7en",
"Schindler's List",
"The Dark Knight Rises",
"Inglourious Basterds",
"The Usual Suspects",
"The Avengers",
"The Shawshank Redemption",
"Django Unchained",
"The Godfather: Part III",
"The Social Network",
"The Terminator",
"The Big Lebowski",
"The Truman Show",
"The Grand Budapest Hotel",
"The Sixth Sense",
"Shutter Island",
"The Revenant",
"The Shining",
"Blade Runner 2049",
"The Departed",
"The Breakfast Club",
"The Princess Bride",
"The Wizard of Oz",
"The Sound of Music",
"The Graduate",
"The Rocky Horror Picture Show",
"The King's Speech",
"The Godfather: Part II",
"The Great Gatsby",
"The Social Network",
"The Lion King",
"The Truman Show",
"The Godfather: Part III",
"The Grand Budapest Hotel",
"The Sixth Sense",
"The Princess Bride",
"The Wizard of Oz",
"The Sound of Music",
"The Graduate",
"The Rocky Horror Picture Show",
"The King's Speech",
"The Godfather: Part II",
"The Great Gatsby",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas",
"The Silence of the Lambs",
"Star Wars: Episode V - The Empire Strikes Back",
"Saving Private Ryan",
"The Green Mile",
"Gladiator",
"Titanic",
"Interstellar",
"The Prestige",
"Se7en",
"Inglourious Basterds",
"The Usual Suspects",
"The Avengers",
"Django Unchained",
"The Godfather: Part III",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas",
"The Silence of the Lambs",
"Star Wars: Episode V - The Empire Strikes Back",
"Saving Private Ryan",
"The Green Mile",
"Gladiator",
"The Departed",
"Titanic",
"Interstellar",
"The Prestige",
"Se7en",
"Inglourious Basterds",
"The Usual Suspects",
"The Avengers",
"Django Unchained",
"The Godfather: Part III",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas",
"The Silence of the Lambs",
"Star Wars: Episode V - The Empire Strikes Back",
"Saving Private Ryan",
"The Green Mile",
"Gladiator",
"The Departed",
"Titanic",
"Interstellar",
"The Prestige",
"Se7en",
"Inglourious Basterds",
"The Usual Suspects",
"The Avengers",
"Django Unchained",
"The Godfather: Part III",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas",
"The Silence of the Lambs",
"Star Wars: Episode V - The Empire Strikes Back",
"Saving Private Ryan",
"The Green Mile",
"Gladiator",
"The Departed",
"Titanic",
"Interstellar",
"The Prestige",
"Se7en",
"Inglourious Basterds",
"The Usual Suspects",
"The Avengers",
"Django Unchained",
"The Godfather: Part III",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas",
"The Silence of the Lambs",
"Star Wars: Episode V - The Empire Strikes Back",
"Saving Private Ryan",
"The Green Mile",
"Gladiator",
"The Departed",
"Titanic",
"Interstellar",
"The Prestige",
"Se7en",
"Inglourious Basterds",
"The Usual Suspects",
"The Avengers",
"Django Unchained",
"The Godfather: Part III",
"The Shawshank Redemption",
"The Dark Knight",
"Schindler's List",
"Pulp Fiction",
"Forrest Gump",
"Fight Club",
"Inception",
"The Matrix",
"Goodfellas","Ajwain",
"Amchur",
"Anardana",
"Asafoetida",
"Basil",
"Bay Leaf",
"Black Cardamom",
"Black Cumin",
"Black Mustard Seeds",
"Black Pepper",
"Black Salt",
"Brown Mustard Seeds",
"Cardamom",
"Carom Seeds",
"Cassia Bark",
"Celery Seeds",
"Chaat Masala",
"Chilli Powder",
"Cinnamon",
"Cloves",
"Coriander Powder",
"Coriander Seeds",
"Cumin Powder",
"Cumin Seeds",
"Curry Leaves",
"Dried Fenugreek Leaves",
"Fennel Seeds",
"Fenugreek Seeds",
"Garam Masala",
"Garlic Powder",
"Ginger Powder",
"Green Cardamom",
"Hing",
"Kalonji",
"Kesar",
"Khada Masala",
"Khus Khus",
"Lemon Grass",
"Mace",
"Mango Powder",
"Mint Leaves",
"Mustard Oil",
"Mustard Seeds",
"Nutmeg",
"Onion Powder",
"Paprika",
"Poppy Seeds",
"Red Chilli Flakes",
"Red Chilli Powder",
"Rock Salt",
"Saffron",
"Sesame Seeds",
"Star Anise",
"Tamarind",
"Turmeric",
"White Pepper",
"Aamchur",
"Achari Masala",
"Ajmoda",
"Ambula",
"Aniseed",
"Arrowroot",
"Avarampoo",
"Beads",
"Biryani Masala",
"Bombil",
"Butter Pepper",
"Camphor",
"Caraway Seeds",
"Cashew Nuts",
"Castor Sugar",
"Charnushka",
"Chawli",
"Chebulic Myrobalan",
"Chilies",
"Chironji",
"Chow Chow",
"Cinnamon Stick",
"Clove",
"Coriander",
"Dried Coconut",
"Dry Dates",
"Dry Ginger",
"Dry Roasted Fenugreek Seeds",
"Flax Seeds",
"Galangal",
"Garlic",
"Ghee",
"Ginger",
"Gokhru",
"Gram Flour",
"Green Cardamom Seeds",
"Green Chilli",
"Green Chillies",
"Green Coriander",
"Green Ginger",
"Green Mango",
"Green Mint Leaves",
"Green Pepper",
"Ground Ginger",
"Gur",
"Haldi",
"Haldi Powder",
"Harad",
"Heeng",
"Himalayan Pink Salt",
"Himalayan Rock Salt",
"Indian Gooseberry",
"Indian Nutmeg",
"Indian Paprika",
"Indian Saffron",
"Indian Spices",
"Jaljeera Masala",
"Javitri",
"Jeera",
"Jeera Powder",

"Taj Mahal, Agra, Uttar Pradesh",
"Red Fort, Delhi",
"Jaipur, Rajasthan (Pink City)",
"Varanasi, Uttar Pradesh",
"Goa Beaches",
"Kerala Backwaters",
"Hampi, Karnataka",
"Rishikesh, Uttarakhand",
"Ladakh, Jammu and Kashmir",
"Mysore Palace, Karnataka",
"Khajuraho Temples, Madhya Pradesh",
"Jaisalmer Fort, Rajasthan",
"Darjeeling, West Bengal",
"Udaipur, Rajasthan (City of Lakes)",
"Ajanta and Ellora Caves, Maharashtra",
"Fatehpur Sikri, Uttar Pradesh",
"Konark Sun Temple, Odisha",
"Amritsar, Punjab (Golden Temple)",
"Ranthambore National Park, Rajasthan",
"Srinagar, Jammu and Kashmir (Dal Lake)",
"Jim Corbett National Park, Uttarakhand",
"Bodh Gaya, Bihar",
"Mahabalipuram, Tamil Nadu",
"Shimla, Himachal Pradesh",
"Haridwar, Uttarakhand",
"Munnar, Kerala",
"Pondicherry",
"Delhi, India Gate",
"Kanyakumari, Tamil Nadu",
"Khajjiar, Himachal Pradesh (Mini Switzerland of India)",
"Nainital, Uttarakhand",
"Agra Fort, Uttar Pradesh",
"Mumbai, Maharashtra (Gateway of India)",
"Hampi, Karnataka",
"Jodhpur, Rajasthan (Blue City)",
"Mahabodhi Temple, Bodh Gaya, Bihar",
"Periyar Wildlife Sanctuary, Kerala",
"Jantar Mantar, Jaipur, Rajasthan",
"Konark Beach, Odisha",
"Chittorgarh Fort, Rajasthan",
"Ajmer, Rajasthan (Ajmer Sharif Dargah)",
"Gulmarg, Jammu and Kashmir",
"Alleppey Backwaters, Kerala",
"Ranikhet, Uttarakhand",
"Tawang Monastery, Arunachal Pradesh",
"Andaman and Nicobar Islands",
"Mathura and Vrindavan, Uttar Pradesh",
"Belur Math, West Bengal",
"Kumbhalgarh Fort, Rajasthan",
"Puri Beach, Odisha",
"Elephanta Caves, Maharashtra",
"Havelock Island, Andaman and Nicobar Islands",
"Madurai, Tamil Nadu (Meenakshi Temple)",
"Valley of Flowers, Uttarakhand",
"Chitrakoot, Madhya Pradesh",
"Dudhsagar Falls, Goa",
"Qutub Minar, Delhi",
"Tirupati, Andhra Pradesh (Tirumala Venkateswara Temple)",
"Shillong, Meghalaya",
"Manali, Himachal Pradesh",
"Ajmer, Rajasthan",
"Sanchi Stupa, Madhya Pradesh",
"Kodaikanal, Tamil Nadu",
"Dharamshala, Himachal Pradesh",
"Alleppey, Kerala (Alappuzha)",
"Orchha, Madhya Pradesh",
"Panchmarhi, Madhya Pradesh",
"Ranakpur Jain Temple, Rajasthan",
"Kanchipuram, Tamil Nadu",
"Ajanta Caves, Maharashtra",
"Badrinath Temple, Uttarakhand",
"Rameshwaram, Tamil Nadu",
"Gwalior Fort, Madhya Pradesh",
"Chilika Lake, Odisha",
"Hampi, Karnataka (Vijayanagara)",
"Somnath Temple, Gujarat",
"Cherrapunji, Meghalaya",
"Mahabaleshwar, Maharashtra",
"Dhanaulti, Uttarakhand",
"Ujjain, Madhya Pradesh",
"Kaziranga National Park, Assam",
"Dzukou Valley, Nagaland",
"Dwarka, Gujarat",
"Hampi, Karnataka (Vijaya Vittala Temple)",
"Lonavala, Maharashtra",
"Rann of Kutch, Gujarat",
"Matheran, Maharashtra",
"Chitrakoot Falls, Chhattisgarh",
"Thekkady, Kerala",
"Tarkarli Beach, Maharashtra",
"Nalanda, Bihar",
"Bharatpur Bird Sanctuary, Rajasthan",
"Gokarna, Karnataka",
"Gir National Park, Gujarat",
"Lachung, Sikkim",
"Panchgani, Maharashtra",
"Mahabaleshwar, Maharashtra",
"Bikaner, Rajasthan",
"Chota Char Dham, Uttarakhand",
"Kumbakonam, Tamil Nadu",
"Hemis Monastery, Ladakh",
"Bishnupur Terracotta Temples, West Bengal",
"Binsar, Uttarakhand",
"Pushkar, Rajasthan",
"Coorg, Karnataka",
"Pachmarhi, Madhya Pradesh",
"Mararikulam, Kerala",
"Almora, Uttarakhand",
"Pelling, Sikkim",
"Narkanda, Himachal Pradesh",
"Pahalgam, Jammu and Kashmir",
"Chamba, Himachal Pradesh",
"Srirangapatna, Karnataka",
"Coonoor, Tamil Nadu",
"Digha, West Bengal",
"Kausani, Uttarakhand",
"Mandu, Madhya Pradesh",
"Auli, Uttarakhand",
"Panna National Park, Madhya Pradesh",
"Orchha, Madhya Pradesh",
"Chidambaram, Tamil Nadu",
"Hogenakkal Falls, Tamil Nadu",
"Dooars, West Bengal",
"Diu, Daman and Diu",
"Bhuj, Gujarat",
"Kurnool, Andhra Pradesh",
"Bhimtal, Uttarakhand",
"Shirdi, Maharashtra",
"Ratnagiri, Maharashtra",
"Kanyakumari, Tamil Nadu",
"Barkot, Uttarakhand",
"Mukteshwar, Uttarakhand",
"Thiruvananthapuram, Kerala",
"Shivpuri, Madhya Pradesh",
"Kodaikanal, Tamil Nadu",
"Khimsar, Rajasthan",
"Gomukh, Uttarakhand",
"Coimbatore, Tamil Nadu",
"Mandawa, Rajasthan",
"Kanatal, Uttarakhand",
"Parwanoo, Himachal Pradesh",
"Tiruchirappalli, Tamil Nadu",
"Rishikesh, Uttarakhand",
"Kozhikode, Kerala",
"Khajjiar, Himachal Pradesh",
"Chikmagalur, Karnataka",
"Churu, Rajasthan",
"Bandhavgarh National Park, Madhya Pradesh",
"Badami",
"Spaghetti Carbonara",
"Chicken Tikka Masala",
"Vegetable Stir-Fry",
"Homemade Pizza",
"Mushroom Risotto",
"Grilled Salmon",
"Tacos",
"Vegetable Curry",
"Hamburger with Homemade Fries",
"Caprese Salad",
"Chicken Caesar Salad",
"Pasta Primavera",
"Beef Stir-Fry",
"Shrimp Scampi",
"Vegetarian Chili",
"Baked Macaroni and Cheese",
"Lemon Garlic Roast Chicken",
"Ratatouille",
"Pad Thai",
"Beef Stroganoff",
"Baked Ziti",
"Fish Tacos",
"Greek Salad",
"Chicken Alfredo",
"Veggie Quesadillas",
"Thai Green Curry",
"BBQ Ribs",
"Eggplant Parmesan",
"Chicken Satay",
"Lentil Soup",
"Stuffed Bell Peppers",
"Chicken Enchiladas",
"Teriyaki Salmon",
"Caesar Salad Wrap",
"Quinoa Salad",
"Spinach and Feta Stuffed Chicken",
"Margherita Pizza",
"Beef and Broccoli Stir-Fry",
"Coconut Curry Chicken",
"Butternut Squash Soup",
"Philly Cheesesteak Sandwich",
"Greek Gyros",
"Mushroom and Spinach Quesadillas",
"Roast Beef with Mashed Potatoes",
"Falafel with Hummus",
"Hawaiian Poke Bowl",
"Minestrone Soup",
"Baked Teriyaki Chicken",
"Tuna Nicoise Salad",
"Sweet and Sour Pork",
"Chicken Shawarma",
"Spinach Lasagna",
"Garlic Butter Shrimp",
"Mexican Street Corn",
"Chicken and Rice Casserole",
"Teriyaki Beef Skewers",
"Panzanella Salad",
"Beef Wellington",
"Mushroom Soup",
"Margherita Flatbread",
"Cucumber Avocado Salad",
"Lemon Herb Roasted Potatoes",
"Thai Peanut Noodles",
"Chicken Fajitas",
"Tomato Basil Bruschetta",
"Shepherd's Pie",
"Baked Cod with Lemon Butter",
"Greek Spanakopita",
"Sweet Potato and Black Bean Enchiladas",
"Beef Kebabs",
"Caesar Salad with Grilled Shrimp",
"Mushroom Risotto Stuffed Peppers",
"Caprese Stuffed Portobello Mushrooms",
"Ratatouille Tart",
"Chicken Tortilla Soup",
"Moroccan Tagine",
"Eggplant Rollatini",
"Garlic Parmesan Roasted Broccoli",
"Lemon Herb Grilled Chicken",
"Veggie Pad Thai",
"Quinoa Stuffed Bell Peppers",
"Hawaiian BBQ Chicken Pizza",
"Lentil Shepherd's Pie",
"Coconut Curry Lentil Soup",
"Greek Lemon Chicken Soup",
"BBQ Pulled Pork Sandwiches",
"Black Bean Tacos",
"Chicken Lettuce Wraps",
"Mushroom and Spinach Stuffed Shells",
"Thai Basil Fried Rice",
"Garlic Butter Steak Bites",
"Mediterranean Couscous Salad",
"Tomato Basil Mozzarella Flatbread",
"Veggie Spring Rolls",
"Chicken Piccata",
"Pesto Pasta",
"Stuffed Acorn Squash",
"Creamy Mushroom and Spinach Pasta",
"Honey Garlic Glazed Salmon",
"Butternut Squash Risotto",
"Spicy Korean Beef Bowl",
"Caprese Chicken",
"BBQ Chicken Salad",
"Vegetarian Sushi Rolls",
"Chicken Parmesan",
"Shrimp and Avocado Salad",
"Garlic Butter Herb Pork Chops",
"Greek Orzo Salad",
"Teriyaki Tofu Stir-Fry",
"Tomato Basil Garlic Pasta",
"Veggie Fajita Bowls",
"Pesto Chicken Panini",
"Ratatouille Stuffed Peppers",
"Mediterranean Stuffed Chicken",
"Sweet and Sour Chicken",
"Black Bean Soup",
"Cauliflower Fried Rice",
"Spinach and Ricotta Stuffed Shells",
"Lemon Garlic Shrimp Pasta",
"Thai Coconut Soup",
"Grilled Vegetable Skewers",
"Beef and Mushroom Stroganoff",
"Caprese Quinoa Salad",
"Chicken Pesto Pasta",
"Hawaiian Teriyaki Chicken Skewers",
"Mushroom Spinach Quiche",
"Mexican Quinoa Salad",
"Honey Sriracha Glazed Salmon",
"Garlic Herb Roasted Chicken Thighs",
"Lemon Garlic Butter Shrimp Scampi",
"Mediterranean Grilled Lamb Chops",
"Spicy Tofu Stir-Fry",
"Hello",
"Goodbye",
"Please",
"Thank you",
"Sorry",
"Yes",
"No",
"Excuse me",
"Help",
"Love",
"Friend",
"Family",
"Food",
"Water",
"Sleep",
"Eat",
"Drink",
"Smile",
"Laugh",
"Cry",
"Happy",
"Sad",
"Angry",
"Excited",
"Tired",
"Hungry",
"Thirsty",
"Cold",
"Hot",
"Beautiful",
"Ugly",
"Pretty",
"Handsome",
"Smart",
"Funny",
"Serious",
"Busy",
"Bored",
"Happy",
"Sad",
"Funny",
"Serious",
"Strong",
"Weak",
"Brave",
"Fearful",
"Kind",
"Mean",
"Generous",
"Selfish",
"Honest",
"Dishonest",
"Polite",
"Rude",
"Quiet",
"Loud",
"Clean",
"Dirty",
"Hard",
"Soft",
"Fast",
"Slow",
"Early",
"Late",
"Big",
"Small",
"Long",
"Short",
"Tall",
"Short",
"Wide",
"Narrow",
"Heavy",
"Light",
"Dark",
"Bright",
"Old",
"New",
"Young",
"Old",
"Simple",
"Complex",
"Easy",
"Difficult",
"Right",
"Wrong",
"True",
"False",
"Open",
"Closed",
"Empty",
"Full",
"Far",
"Near",
"High",
"Low",
"Big",
"Small",
"More",
"Less",
"Best",
"Worst",
"Many",
"Few",
"All",
"None",
"Some",
"None",
"Always",
"Never",
"Often",
"Sometimes",
"Day",
"Night",
"Morning",
"Afternoon",
"Evening",
"Sun",
"Moon",
"Star",
"Sky",
"Earth",
"Ocean",
"River",
"Lake",
"Mountain",
"Hill",
"Valley",
"Desert",
"Forest",
"Tree",
"Flower",
"Grass",
"Leaf",
"Rock",
"Stone",
"Sand",
"Soil",
"Air",
"Wind",
"Cloud",
"Rain",
"Snow",
"Ice",
"Fire",
"Smoke",
"Light",
"Shadow",
"Heat",
"Cold",
"Sound",
"Music",
"Noise",
"Silence",
"Color",
"Red",
"Blue",
"Green",
"Yellow",
"Orange",
"Purple",
"Pink",
"White",
"Black",
"Gray",
"Brown",
"Silver",
"Gold",
"Metal",
"Wood",
"Plastic",
"Glass",
"Paper",
"Cloth",
"Cotton",
"Silk",
"Wool",
"Leather",
"Rubber",
"Plastic",
"Food",
"Fruit",
"Vegetable",
"Bread",
"Rice",
"Pasta",
"Meat",
"Fish",
"Chicken",
"Beef",
"Pork",
"Egg",
"Cheese",
"Milk",
"Butter",
"Sugar",
"Salt",
"Pepper",
"Spice",
"Oil",
"Water",
"Tea",
"Coffee",
"Juice",
"Soda",
"Wine",
"Beer",
"Whiskey",
"Vodka",
"Rum",
"Gin",
"Brandy",
"Champagne",
"Cocktail",
"Salad",
"Soup",
"Sandwich",
"Pizza",
"Burger",
"Taco",
"Burrito",
"Sushi",
"Noodle",
"Dumpling",
"Cake",
"Cookie",
"Pie",
"Ice cream",
"Candy",
"Chocolate",
"Snack",
"Appetizer",
"Main course",
"Dessert",
"Plate",
"Bowl",
"Fork",
"Spoon",
"Knife",
"Glass",
"Cup",
"Mug",
"Tray",
"Dish",
"Pan",
"Pot",
"Oven",
"Stove",
"Microwave",
"Grill",
"Blender",
"Toaster",
"Mixer",
"Juicer",
"Cook",
"Bake",
"Fry",
"Boil",
"Grill",
"Roast",
"Steam",
"Chop",
"Slice",
"Dice",
"Grate",
"Peel",
"Stir",
"Mix",
"Pour",
"Spread",
"Measure",
"Taste",
"Smell",
"See",
"Hear",
"Touch",
"Cook",
"Eat",
"Drink",
"Sleep",
"Rest",
"Relax",
"Exercise",
"Walk",
"Run",
"Jump",
"Swim",
"Climb",
"Dance",
"Sing",
"Play",
"Read",
"Write",
"Draw",
"Paint",
"Build",
"Create",
"Imagine",
"Dream",
"Greek Chicken Souvlaki",
"Caprese Chicken Pasta","able",
"acid",
"age",
"ago",
"air",
"all",
"am",
"an",
"and",
"any",
"ape",
"apple",
"are",
"arm",
"art",
"ash",
"at",
"ate",
"awe",
"axe",
"bad",
"bag",
"ball",
"bam",
"ban",
"bat",
"bath",
"bay",
"be",
"bee",
"beat",
"bed",
"bee",
"beg",
"bell",
"bet",
"big",
"bike",
"bill",
"bin",
"bird",
"bit",
"black",
"blast",
"blew",
"block",
"blue",
"boat",
"bog",
"book",
"boot",
"born",
"both",
"bow",
"box",
"boy",
"brag",
"brain",
"branch",
"brave",
"bread",
"break",
"brief",
"bring",
"broke",
"brush",
"bubble",
"bug",
"build",
"bulk",
"burn",
"bus",
"bush",
"bust",
"busy",
"but",
"buy",
"by",
"cage",
"cake",
"call",
"calm",
"came",
"camp",
"can",
"cap",
"car",
"card",
"care",
"coat",
"cold",
"comb",
"come",
"cook",
"cool",
"corn",
"cot",
"cow",
"coat",
"coin",
"cut",
"cup",
"dab",
"dad",
"dam",
"dance",
"dare",
"dark",
"date",
"day",
"dead",
"deal",
"deep",
"deer",
"den",
"dew",
"die",
"dig",
"dim",
"din",
"dine",
"dip",
"dog",
"door",
"dot",
"down",
"drag",
"draw",
"dream",
"dress",
"drift",
"drop",
"drum",
"dry",
"duck",
"dust",
"ear",
"eat",
"egg",
"end",
"even",
"ever",
"eye",
"face",
"fade",
"fail",
"fair",
"fall",
"fame",
"fan",
"farm",
"far",
"fast",
"fat",
"fear",
"feel",
"few",
"fill",
"find",
"fine",
"fire",
"first",
"fit",
"fix",
"flat",
"flee",
"flew",
"flip",
"flop",
"fly",
"foam",
"food",
"foot",
"for",
"forest",
"fork",
"form",
"fort",
"found",
"four",
"free",
"friend",
"from",
"front",
"fruit",
"full",
"fun",
"funny",
"fur",
"gain",
"game",
"gas",
"gave",
"gear",
"get",
"gift",
"girl",
"give",
"glad",
"go",
"goal",
"gold",
"gone",
"good",
"grab",
"gray",
"grew",
"grass",
"green",
"grip",
"ground",
"group",
"grow",
"guide",
"gun",
"hair",
"hall",
"ham",
"hand",
"hang",
"happy",
"hard",
"hare",
"harm",
"hate",
"have",
"hawk",
"he",
"head",
"hear",
"heart",
"heat",
"heavy",
"her",
"here",
"hide",
"high",
"hill",
"him",
"hint",
"hip",
"hit",
"hold",
"hole",
"home",
"hone",
"hood",
"hook",
"hope",
"hop",
"horn",
"horse",
"hot",
"hour",
"house",
"how",
"hug",
"hum",
"hunt",
"hurry",
"hurt",
"I",
"ice",
"if",
"in",
"inch",
"insect",
"into",
"is",
"it",
"jam",
"jar",
"jet",
"jig",
"job",
"jog",
"join",
"joke",
"jump",
"just",
"keen",
"kept",
"key",
"kid",
"kill",
"kind",
"king",
"kiss",
"kite",
"knee",
"knew",
"knife",
"knob",
"knot",
"know",
"lab",
"lack",
"lake",
"land",
"lap",
"last",
"late",
"laugh",
"lay",
"lead",
"leaf",
"lean",
"learn",
"leave",
"led",
"left",
"leg",
"less",
"let",
"lick",
"lid",
"lie",
"life",
"lift",
"light",
"like",
"line",
"lip",
"list",
"live",
"load",
"loaf",
"loan",
"lock",
"long",
"look",
"loose",
"lost",
"loud",
"love",
"low",
"lump",
"lunch",
"lye",
"made",
"mail",
"main",
"make",
"man",
"map",
"mark",
"mass",
"mast",
"may",
"me",
"mean",
"meant",
"meat",
"meet",
"men",
"melt",
"mend",
"menu",
"mere",
"mess",
"met",
"mice",
"mile",
"milk",
"mill",
"mind",
"mine",
"mint",
"miss",
"mist",
"mix",
"moan",
"mob",
"mock",
"moist",
"mold",
"mom",
"mood",
"moon",
"mop",
"more",
"morn",
"most",
"moth",
"motor",
"mound",
"mount",
"mouse",
"mouth",
"move",
"much",
"mud",
"mug",
"mule",
"must",
"my",
"nail",
"name",
"nap",
"near",
"neck",
"need",
"neon",
"nerve",
"never",
"new",
"next",
"nice",
"night",
"nine",
"no",
"nod",
"none",
"noon",
"nor",
"nose",
"not",
"now",
"nut",
"oak",
"oar",
"oat",
"odd",
"of",
"off",
"often",
"oil",
"okay",
"old",
"on",
"one",
"only",
"open",
"or",
"orb",
"our",
"out",
"oval",
"oven",
"over",
"owl",
"own",
"pack",
"page",
"paid",
"pail",
"pain",
"pair",
"pale",
"pan",
"pane",
"pan",
"paper",
"par",
"part",
"pass",
"past",
"pat",
"path",
"pay",
"pea",
"peal",
"pear",
"peck",
"pee",
"peel",
"peep",
"peg",
"pen",
"per",
"pet",
"pew",
"phone",
"pic",
"pick",
"pie",
"peg",
"pig",
"pile",
"pill",
"pin",
"ping",
"pink",
"pit",
"plan",
"play",
"plot",
"plow",
"plum",
"plus",
"poem",
"point",
"pole",
"pol",
"pool",
"poor",
"pop",
"post",
"pot",
"pow",
"pour",
"powder",
"pow",
"puff",
"pull",
"pump",
"pun",
"pure",
"push",
"put",
"quick",
"quiet",
"quit",
"quiz",
"rag",
"rail",
"rain",
"ram",
"ramp",
"ran",
"rat",
"rate",
"raw",
"ray",
"red",
"rest",
"rib",
"rib",
"ride",
"rig",
"right",
"ring",
"rip",
"ripe",
"roar",
"rock",
"rod",
"roll",
"room",
"rose",
"rot",
"rough",
"round",
"rove",
"row",
"royal",
"rub",
"rug",
"ruin",
"rule",
"run",
"rush",
"rust",
"sack",
"sad",
"safe",
"sail",
"sale",
"salt",
"same",
"sand",
"sane",
"save",
"saw",
"say",
"scale",
"scared",
"scarf",
"scary",
"school",
"scoop",
"score",
"scorn",
"scrap",
"screen",
"sea",
"seat",
"second",
"see",
"seed",
"seem",
"seen",
"self",
"send",
"sent",
"set",
"seven",
"shake",
"shall",
"shame",
"shape",
"share",
"sharp",
"she",
"shell",
"shift",
"shine",
"shirt",
"shock",
"shop",
"short",
"shot",
"should",
"shout",
"show",
"shrug",
"shut",
"sick",
"side",
"sign",
"silk",
"silly",
"silver",
"sim",
"sin",
"sing",
"sink",
"sip",
"sir",
"sis",
"sit",
"size",
"ski",
"skin",
"skip",
"sky",
"slap",
"slash",
"slate",
"sleep",
"slip",
"slow",
"small",
"smart",
"smile",
"smoke",
"snack",
"snag",
"snake",
"snap",
"snip",
"snow",
"so",
"soap",
"soft",
"sold",
"some",
"son",
"song",
"soon",
"sore",
"sort",
"sound",
"soup",
"south",
"space",
"spade",
"span",
"spare",
"spark",
"speak",
"speed",
"spell",
"spend",
"spice",
"spill",
"spin",
"split",
"spoil",
"spoon",
"spot",
"spray",
"spread",
"spring",
"spy",
"square",
"stand",
"star",
"start",
"starve",
"stay",
"steal",
"steam",
"steel",
"steep",
"steer",
"step",
"stick",
"stiff",
"still",
"stock",
"stole",
"stone",
"stood",
"stop",
"store",
"storm",
"stove",
"stray",
"strike",
"strong",
"stuck",
"stump",
"sub",
"such",
"sugar",
"suit",
"sum",
"sun",
"sup",
"super",
"sure",
"surf",
"swam",
"swan",
"sweet",
"swim",
"swing",
"switch",
"sword",
"tack",
"tail",
"take",
"tale",
"talk",
"tall",
"tank",
"tap",
"tar",
"task",
"taste",
"tax",
"tea",
"teach",
"team",
"tear",
"tease",
"tee",
"teen",
"teeth",
"tell",
"ten",
"thank",
"theme",
"then",
"there",
"these",
"they",
"thin",
"thing",
"think",
"this",
"those",
"three",
"threw",
"through",
"tie",
"tiger",
"tight",
"time",
"tin",
"tip",
"tire",
"to",
"toad",
"toast",
"toe",
"told",
"tool",
"took",
"tooth",
"top",
"toss",
"tote",
"tour",
"towel",
"tower",
"toy",
"trace",
"track",
"trade",
"trail",
"train",
"trap",
"tree",
"trip",
"truck",
"true",
"trust",
"try",
"tub",
"tuck",
"tug",
"tune",
"turn",
"twice",
"twin",
"twist",
"ugly",
"under",
"unit",
"until",
"up",
"upon",
"us",
"use",
"van",
"very",
"vet",
"view",
"viol",
"violet",
"vote",
"wade",
"wage",
"wail",
"wait",
"wake",
"walk",
"wall",
"want",
"ward",
"warm",
"warn",
"wart",
"wash",
"waste",
"watch",
"water",
"wave",
"wax",
"way",
"we",
"weak",
"wean",
"wear",
"weave",
"web",
"wed",
"weed",
"week",
"weep",
"weight",
"welcome",
"well",
"went",
"west",
"wet",
"whale",
"what",
"when",
"where",
"which",
"whip",
"whir",
"whisk",
"whit",
"white",
"who",
"whole",
"whom",
"whose",
"why",
"wick",
"wide",
"wife",
"wild",
"will",
"win",
"wind",
"wine",
"wing",
"wink",
"wire",
"wise",
"wish",
"with",
"wolf",
"wool",
"word",
"work",
"world",
"worm",
"worn",
"worse",
"worth",
"would",
"wound",
"wrap",
"wrist",
"write",
"wrong",
"yea",
"year",
"yell",
"yellow",
"yes",
"yet",
"yolk",
"you",
"young",
"your",
"zap",
"zeal",
"zebra",
"zero",
"zest",
"zig",
"zip",
"zone",
"zoo",
"a",
"aa",
"ab",
"ad",
"ae",
"ag",
"ah",
"ai",
"al",
"am",
"an",
"ap",
"ar",
"as",
"at",
"aw",
"ay",
"ba",
"be",
"bo",
"by",
"da",
"de",
"do",
"ed",
"ef",
"eh",
"el",
"em"]
                    ],
                random: () => {
                    let list = BING_AUTOSEARCH.search.engine.terms.lists[Math.floor(Math.random() * BING_AUTOSEARCH.search.engine.terms.lists.length)];
                    let term = list[Math.floor(Math.random() * list.length)];

                    return term;
                }
            },
            form: {
                params: [
                    "QBLH", //Main page textbox suggestion click
                    "QBRE", //Search page textbox suggestion click
                    "HDRSC1", //Search tabmenu click 
                    "LGWQS1", "LGWQS2", "LGWQS3", //Left sidebar suggestion click
                    "R5FD", "R5FD1", "R5FD2", "R5FD3", "R5FD4", "R5FD5", "R5FD6", "R5FD7", //Right sidebar suggestion click
                    "QSRE1", "QSRE2", "QSRE3", "QSRE4", "QSRE5", "QSRE6", "QSRE7", "QSRE8", //Footer suggestion click
                ],
                random: () => {
                    return BING_AUTOSEARCH.search.engine.form.params[Math.floor(Math.random() * BING_AUTOSEARCH.search.engine.form.params.length)]
                }
            },
            window: {
                open: (search) => {
                    try {
                        let w = window.open(search.url);

                        if (w) {
                            setTimeout(() => {
                                w.close();
                            }, (BING_AUTOSEARCH.search.interval <= 15000 ? BING_AUTOSEARCH.search.interval : 15000) - 500);
                        }
                    }
                    catch (e) { }
                }
            },
            iframe: {
                add: (search) => {
                    let iframe = document.createElement("iframe");

                    iframe.setAttribute("src", search.url);
                    iframe.setAttribute("title", search.term);
                    iframe.setAttribute("data-index", search.index);

                    if (BING_AUTOSEARCH.elements.div.bing.firstChild)
                        BING_AUTOSEARCH.elements.div.bing.removeChild(BING_AUTOSEARCH.elements.div.bing.firstChild);

                    BING_AUTOSEARCH.elements.div.bing.appendChild(iframe);
                }
            },
            settings: {
                toString: () => {
                    try {
                        return `${BING_AUTOSEARCH.elements.select.limit.options[BING_AUTOSEARCH.elements.select.limit.selectedIndex].text}, ${BING_AUTOSEARCH.elements.select.interval.options[BING_AUTOSEARCH.elements.select.interval.selectedIndex].text} interval and Multi-tab Mode ${BING_AUTOSEARCH.elements.select.multitab.options[BING_AUTOSEARCH.elements.select.multitab.selectedIndex].text}`;
                    }
                    catch (e) {
                        return `Oops! There was an error loading the settings, please clear your browser cookies and reload the page to continue`;
                    }
                }
            },
            progress: {
                update: (search) => {
                    let progress = `(${search.index < 10 ? "0" + search.index : search.index}/${BING_AUTOSEARCH.search.limit < 10 ? "0" + BING_AUTOSEARCH.search.limit : BING_AUTOSEARCH.search.limit})`;

                    document.title = `${progress} - Bing Auto Search Running`;
                    BING_AUTOSEARCH.elements.span.progress.innerText = progress;
                }
            },
            timer: {
                next: null,
                complete: null,
                toClockFormat: (milliseconds, showHours = false) => {
                    let hrs = Math.floor((milliseconds / (1000 * 60 * 60)) % 24);
                    let min = Math.floor((milliseconds / 1000 / 60) % 60);
                    let sec = Math.floor((milliseconds / 1000) % 60);

                    return `${showHours ? String(hrs).padStart(2, '0') + ":" : ""}${String(min).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
                },
                updateEstimatedTime: (search) => {
                    let now = new Date();
                    let next = new Date(now.getTime() + BING_AUTOSEARCH.search.interval);
                    let complete = new Date(now.getTime() + (BING_AUTOSEARCH.search.interval * (BING_AUTOSEARCH.search.limit - search.index)));

                    if (search.index === BING_AUTOSEARCH.search.limit)
                        next = now;

                    BING_AUTOSEARCH.search.engine.timer.next = next;
                    BING_AUTOSEARCH.search.engine.timer.complete = complete;
                },
                run: () => {
                    let now = new Date();
                    let next = (BING_AUTOSEARCH.search.engine.timer.next - now);
                    let complete = (BING_AUTOSEARCH.search.engine.timer.complete - now);

                    if (complete >= 0) {
                        BING_AUTOSEARCH.elements.div.timer.innerHTML = `<strong>Auto Search Running:</strong> ${next >= 0 ? `New auto search in ${BING_AUTOSEARCH.search.engine.timer.toClockFormat(next)}` : "Finishing last auto search"}, estimated time to complete ${BING_AUTOSEARCH.search.engine.timer.toClockFormat(complete, true)}.`;

                        setTimeout(() => {
                            BING_AUTOSEARCH.search.engine.timer.run();
                        }, 1000);
                    }
                    else {
                        BING_AUTOSEARCH.elements.div.timer.innerHTML = `<strong>Auto Search Running:</strong> Stopping auto search process...`;
                    }
                }
            }
        },
        generate: () => {
            let searches = new Array();

            do
            {
                let term = BING_AUTOSEARCH.search.engine.terms.random();

                if (!searches.includes(term)) {
                    let index = searches.length + 1;
                    let url = `https://www.bing.com/search?q=${encodeURIComponent(term.toLowerCase())}&FORM=${BING_AUTOSEARCH.search.engine.form.random()}`;
                    let delay = BING_AUTOSEARCH.search.interval * searches.length;

                    searches.push({ term, url, index, delay });
                }

            } while (searches.length < BING_AUTOSEARCH.search.limit)

            return searches;
        },
        start: () => {
            let searches = BING_AUTOSEARCH.search.generate();

            searches.forEach((search) => {
                setTimeout(() => {
                    BING_AUTOSEARCH.search.engine.progress.update(search);
                    BING_AUTOSEARCH.search.engine.timer.updateEstimatedTime(search);

                    if (search.index === BING_AUTOSEARCH.search.limit) {
                        setTimeout(() => {
                            BING_AUTOSEARCH.search.stop();
                        }, (BING_AUTOSEARCH.search.interval <= 15000 ? BING_AUTOSEARCH.search.interval : 15000));
                    }

                    if (search.delay === 0)
                        BING_AUTOSEARCH.search.engine.timer.run();

                    if (!BING_AUTOSEARCH.search.multitab)
                        BING_AUTOSEARCH.search.engine.iframe.add(search);
                    else
                        BING_AUTOSEARCH.search.engine.window.open(search);
                }, search.delay);
            });
        },
        stop: () => {
            window.open("https://rewards.bing.com/pointsbreakdown");

            location.reload();
        }
    },
    load: () => {
        BING_AUTOSEARCH.cookies.load();

        BING_AUTOSEARCH.elements.button.start.addEventListener("click", () => {
            BING_AUTOSEARCH.elements.button.start.style.display = "none";
            BING_AUTOSEARCH.elements.button.stop.style.display = "inline-block";

            BING_AUTOSEARCH.search.start();
        });

        BING_AUTOSEARCH.elements.button.stop.addEventListener("click", () => {
            BING_AUTOSEARCH.search.stop();
        });

        BING_AUTOSEARCH.elements.select.multitab.addEventListener("change", () => {
            BING_AUTOSEARCH.cookies.set("_multitab_mode", BING_AUTOSEARCH.elements.select.multitab.value, 365);
            location.reload();
        });

        BING_AUTOSEARCH.elements.select.limit.addEventListener("change", () => {
            BING_AUTOSEARCH.cookies.set("_search_limit", BING_AUTOSEARCH.elements.select.limit.value, 365);
            location.reload();
        });

        BING_AUTOSEARCH.elements.select.interval.addEventListener("change", () => {
            BING_AUTOSEARCH.cookies.set("_search_interval", BING_AUTOSEARCH.elements.select.interval.value, 365);
            location.reload();
        });

        BING_AUTOSEARCH.elements.div.settings.innerHTML = `<strong>Auto Search Settings:</strong> ${BING_AUTOSEARCH.search.engine.settings.toString()}.`;
    }
};

window.addEventListener("load", () => {
    BING_AUTOSEARCH.load();

    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());
    gtag('config', 'G-YXNCPPFVCW');
});
